#:project ../NeuralNetwork.NumSharp.csproj
#:property PublishAot=false
#:property AllowUnsafeBlocks=true
#:property Nullable=disable
// Edge-case oracle replay for NeuralNetwork.NumSharp.
//
// Source of truth: corpus/keras_edge_oracle.json — real Keras 3 (JAX backend,
// float32) values AND jax.grad gradients, Keras metric classes, scikit-learn
// metrics. Generated by gen_keras_oracle.py; replayed here with NO Python.
//
// A case may carry "expected_ns": NumSharp's DEFINED behavior where it
// intentionally diverges from Keras (each with a reason in "note") — asserted
// against expected_ns and REPORTED, never silent (MisalignedRegistry spirit).
//
// Run from THIS directory:
//   cd examples/NeuralNetwork.NumSharp/tests && dotnet run verify_edge_cases.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using NeuralNetwork.NumSharp.Activations;
using NeuralNetwork.NumSharp.Cost;
using NeuralNetwork.NumSharp.Initializers;
using NeuralNetwork.NumSharp.Layers;
using NeuralNetwork.NumSharp.Metrics;
using NeuralNetwork.NumSharp.MnistMlp;
using NumSharp;
using NumSharp.Backends;

const float RelTol = 1e-4f;
const float AbsTol = 1e-5f;

string corpusPath = Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "corpus", "keras_edge_oracle.json");
if (!File.Exists(corpusPath))
    corpusPath = "corpus/keras_edge_oracle.json";
if (!File.Exists(corpusPath))
{
    Console.WriteLine($"FATAL: corpus not found at {Path.GetFullPath(corpusPath)}");
    return 2;
}

var doc = JsonDocument.Parse(File.ReadAllText(corpusPath));
var meta = doc.RootElement.GetProperty("meta");
Console.WriteLine($"corpus: {meta.GetProperty("cases").GetInt32()} cases | keras {meta.GetProperty("keras").GetString()} " +
                  $"({meta.GetProperty("backend").GetString()}, {meta.GetProperty("floatx").GetString()})");

int pass = 0, fail = 0, excused = 0;

foreach (var c in doc.RootElement.GetProperty("cases").EnumerateArray())
{
    string kind = c.GetProperty("kind").GetString();
    string name = c.GetProperty("name").GetString();
    string note = c.TryGetProperty("note", out var n) ? n.GetString() : "";
    string id = $"{kind}/{name}" + (note.Length > 0 ? $" [{note.Split(' ')[0]}]" : "");

    try
    {
        bool isExcused = c.TryGetProperty("expected_ns", out var expNs);
        JsonElement expected = isExcused ? expNs : c.GetProperty("expected");
        if (isExcused)
        {
            excused++;
            Console.WriteLine($"  excused {id}: {note}");
        }

        switch (kind)
        {
            case "activation":
            {
                NDArray x = ToNDArray(c.GetProperty("inputs").GetProperty("x"));
                BaseActivation act = MakeActivation(name);
                act.Forward(x);
                Assert(id, act.Output, expected);
                break;
            }
            case "activation_grad":
            {
                NDArray x = ToNDArray(c.GetProperty("inputs").GetProperty("x"));
                BaseActivation act = MakeActivation(name);
                act.Forward(x);
                act.Backward(np.ones(x.Shape, NPTypeCode.Single));
                Assert(id, act.InputGrad, expected);
                break;
            }
            case "loss":
            {
                var (cost, preds, labels) = MakeLossCall(name, c);
                NDArray loss = cost.Forward(preds, labels);
                AssertScalar(id, (float)loss, expected);
                break;
            }
            case "loss_grad":
            {
                var (cost, preds, labels) = MakeLossCall(name, c);
                cost.Forward(preds, labels);          // SCE caches softmax here
                NDArray grad = cost.Backward(preds, labels);
                Assert(id, grad, expected);
                break;
            }
            case "metric":
            {
                float actual = RunMetric(name, c);
                AssertScalar(id, actual, expected);
                break;
            }
            case "init_std":
            {
                var shapeDims = c.GetProperty("params").GetProperty("shape").EnumerateArray().Select(e => e.GetInt32()).ToArray();
                BaseInitializer init = BaseInitializer.Get(name);

                // Sample std has SE ≈ std/sqrt(2N) — 4.2% for the (3,3,4,8)
                // conv shape's 288 elements. Mirror the generator: average the
                // std over 5 seeded draws (SE/√5) so the 5% gate is ~2.7σ.
                float stdSum = 0f;
                float maxAbsAll = 0f;
                const int draws = 5;
                for (int s = 0; s < draws; s++)
                {
                    np.random.seed(1234 + s);
                    NDArray w = init.Initialize(new Shape(shapeDims));
                    stdSum += (float)np.std(w);
                    maxAbsAll = Math.Max(maxAbsAll, (float)np.max(np.abs(w)));
                }
                float std = stdSum / draws;
                float target = expected.GetSingle();
                Check(id + " std", Math.Abs(std - target) <= 0.05f * target, $"std={std} keras={target}");
                if (c.TryGetProperty("limit", out var lim))
                    Check(id + " limit", maxAbsAll <= lim.GetSingle() + 1e-6f, $"max={maxAbsAll} limit={lim.GetSingle()}");
                break;
            }
            default:
                Check(id, false, $"unknown kind '{kind}'");
                break;
        }
    }
    catch (Exception ex)
    {
        Check(id, false, $"threw {ex.GetType().Name}: {ex.Message}");
    }
}

Console.WriteLine();
Console.WriteLine($"RESULT: {pass} passed, {fail} failed, {excused} excused-documented divergences");
return fail == 0 ? 0 : 1;

// ======================================================================

void Check(string name, bool ok, string detail = "")
{
    if (ok) pass++;
    else { fail++; Console.WriteLine($"  FAIL {name} {detail}"); }
}

void Assert(string name, NDArray actual, JsonElement expected)
{
    float[] exp = Flatten(expected).ToArray();
    var flat = np.reshape(actual, new Shape((int)actual.size)).astype(NPTypeCode.Single);
    if (flat.size != exp.Length)
    { Check(name, false, $"size {flat.size} != {exp.Length}"); return; }
    for (int i = 0; i < exp.Length; i++)
    {
        if (!FloatClose(flat.GetSingle(i), exp[i]))
        { Check(name, false, $"[{i}] actual={flat.GetSingle(i)} expected={exp[i]}"); return; }
    }
    Check(name, true);
}

void AssertScalar(string name, float actual, JsonElement expected)
{
    float exp = expected.ValueKind == JsonValueKind.String ? ParseSentinel(expected.GetString()) : (float)expected.GetDouble();
    Check(name, FloatClose(actual, exp), $"actual={actual} expected={exp}");
}

bool FloatClose(float a, float b)
{
    if (float.IsNaN(a) || float.IsNaN(b)) return float.IsNaN(a) && float.IsNaN(b);
    if (float.IsInfinity(a) || float.IsInfinity(b)) return a == b;
    float diff = Math.Abs(a - b);
    return diff <= AbsTol || diff <= RelTol * Math.Max(Math.Abs(a), Math.Abs(b));
}

static float ParseSentinel(string s) => s switch
{
    "NaN" => float.NaN,
    "Infinity" => float.PositiveInfinity,
    "-Infinity" => float.NegativeInfinity,
    _ => float.Parse(s),
};

static IEnumerable<float> Flatten(JsonElement e)
{
    switch (e.ValueKind)
    {
        case JsonValueKind.Array:
            foreach (var child in e.EnumerateArray())
                foreach (var v in Flatten(child))
                    yield return v;
            break;
        case JsonValueKind.String:
            yield return ParseSentinel(e.GetString());
            break;
        default:
            yield return (float)e.GetDouble();
            break;
    }
}

static NDArray ToNDArray(JsonElement e)
{
    // 1-D or 2-D float32 from (possibly nested) JSON arrays with sentinels.
    var first = e.EnumerateArray().First();
    if (first.ValueKind == JsonValueKind.Array)
    {
        int rows = e.GetArrayLength(), cols = first.GetArrayLength();
        var nd = np.zeros(new Shape(rows, cols), NPTypeCode.Single);
        int i = 0;
        foreach (var row in e.EnumerateArray())
        {
            int j = 0;
            foreach (var v in row.EnumerateArray())
            {
                nd[$"{i}:{i + 1}"][$":, {j}:{j + 1}"] = (NDArray)ReadFloat(v);
                j++;
            }
            i++;
        }
        return nd;
    }
    float[] vals = e.EnumerateArray().Select(ReadFloat).ToArray();
    return np.array(vals);
}

static float ReadFloat(JsonElement v)
    => v.ValueKind == JsonValueKind.String ? ParseSentinel(v.GetString()) : (float)v.GetDouble();

static int[] ToIntArray(JsonElement e) => e.EnumerateArray().Select(x => x.GetInt32()).ToArray();

static BaseActivation MakeActivation(string name) => name switch
{
    "relu" => new ReLU(),
    "sigmoid" => new Sigmoid(),
    "tanh" => new Tanh(),
    "leaky_relu" => new LeakyReLU(0.3f),
    "elu" => new ELU(1.0f),
    "gelu" => new GELU(),
    "silu" => new SiLU(),
    "softplus" => new Softplus(),
    "selu" => new SELU(),
    "softmax" => new Softmax(),
    _ => throw new ArgumentException($"unknown activation {name}"),
};

static (BaseCost cost, NDArray preds, NDArray labels) MakeLossCall(string name, JsonElement c)
{
    var inputs = c.GetProperty("inputs");
    switch (name)
    {
        case "cce":
            return (new CategoricalCrossentropy(), ToNDArray(inputs.GetProperty("y_pred")), ToNDArray(inputs.GetProperty("y_true")));
        case "scce":
            return (new SparseCategoricalCrossentropy(), ToNDArray(inputs.GetProperty("y_pred")), np.array(ToIntArray(inputs.GetProperty("labels"))));
        case "bce":
            return (new BinaryCrossEntropy(), ToNDArray(inputs.GetProperty("y_pred")), ToNDArray(inputs.GetProperty("y_true")));
        case "huber":
        {
            float delta = (float)c.GetProperty("params").GetProperty("delta").GetDouble();
            return (new Huber(delta), ToNDArray(inputs.GetProperty("y_pred")), ToNDArray(inputs.GetProperty("y_true")));
        }
        case "hinge":
            return (new Hinge(), ToNDArray(inputs.GetProperty("y_pred")), ToNDArray(inputs.GetProperty("y_true")));
        case "kl":
            return (new KLDivergence(), ToNDArray(inputs.GetProperty("y_pred")), ToNDArray(inputs.GetProperty("y_true")));
        case "logcosh":
            return (new LogCosh(), ToNDArray(inputs.GetProperty("y_pred")), ToNDArray(inputs.GetProperty("y_true")));
        case "sce_logits":
            return (new SoftmaxCrossEntropy(), ToNDArray(inputs.GetProperty("logits")), ToNDArray(inputs.GetProperty("y_true")));
        default:
            throw new ArgumentException($"unknown loss {name}");
    }
}

float RunMetric(string name, JsonElement c)
{
    var inputs = c.GetProperty("inputs");
    NDArray yt = ToNDArray(inputs.GetProperty("y_true"));
    NDArray yp = ToNDArray(inputs.GetProperty("y_pred"));
    return name switch
    {
        "precision" => (float)new Precision(0.5f).Calculate(yp, yt),
        "recall" => (float)new Recall(0.5f).Calculate(yp, yt),
        "binary_accuracy" => (float)new BinaryAccuracy().Calculate(yp, yt),
        "top_k" => (float)new TopKCategoricalAccuracy(c.GetProperty("params").GetProperty("k").GetInt32()).Calculate(yp, yt),
        "f1_binary" => (float)new F1Score(F1Average.Binary, 0.5f).Calculate(yp, yt),
        "f1_macro" => (float)new F1Score(F1Average.Macro).Calculate(yp, yt),
        "r2" => (float)new R2Score().Calculate(yp, yt),
        "rmse" => (float)new RootMeanSquaredError().Calculate(yp, yt),
        "accuracy" => (float)new Accuracy().Calculate(yp, yt),
        _ => throw new ArgumentException($"unknown metric {name}"),
    };
}
