#:project ../NeuralNetwork.NumSharp.csproj
#:property PublishAot=false
#:property AllowUnsafeBlocks=true
#:property Nullable=disable
// Edge-case oracle replay for NeuralNetwork.NumSharp.
//
// Source of truth: corpus/keras_edge_oracle.json — real Keras 3 (JAX backend,
// float32) values AND jax.grad gradients, Keras metric classes, scikit-learn
// metrics. Generated by gen_keras_oracle.py; replayed here with NO Python.
//
// A case may carry "expected_ns": NumSharp's DEFINED behavior where it
// intentionally diverges from Keras (each with a reason in "note") — asserted
// against expected_ns and REPORTED, never silent (MisalignedRegistry spirit).
//
// Run from THIS directory:
//   cd examples/NeuralNetwork.NumSharp/tests && dotnet run VerifyKerasOracleTests.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using NeuralNetwork.NumSharp.Activations;
using NeuralNetwork.NumSharp.Cost;
using NeuralNetwork.NumSharp.Initializers;
using NeuralNetwork.NumSharp.Layers;
using NeuralNetwork.NumSharp.Metrics;
using NeuralNetwork.NumSharp.MnistMlp;
using NeuralNetwork.NumSharp.Regularizers;
using NumSharp;
using NumSharp.Backends;

const float RelTol = 1e-4f;
const float AbsTol = 1e-5f;

string corpusPath = Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "corpus", "keras_edge_oracle.json");
if (!File.Exists(corpusPath))
    corpusPath = "corpus/keras_edge_oracle.json";
if (!File.Exists(corpusPath))
{
    Console.WriteLine($"FATAL: corpus not found at {Path.GetFullPath(corpusPath)}");
    return 2;
}

var doc = JsonDocument.Parse(File.ReadAllText(corpusPath));
var meta = doc.RootElement.GetProperty("meta");
Console.WriteLine($"corpus: {meta.GetProperty("cases").GetInt32()} cases | keras {meta.GetProperty("keras").GetString()} " +
                  $"({meta.GetProperty("backend").GetString()}, {meta.GetProperty("floatx").GetString()})");

int pass = 0, fail = 0, excused = 0;

foreach (var c in doc.RootElement.GetProperty("cases").EnumerateArray())
{
    string kind = c.GetProperty("kind").GetString();
    string name = c.GetProperty("name").GetString();
    string note = c.TryGetProperty("note", out var n) ? n.GetString() : "";
    string id = $"{kind}/{name}" + (note.Length > 0 ? $" [{note.Split(' ')[0]}]" : "");

    try
    {
        bool isExcused = c.TryGetProperty("expected_ns", out var expNs);
        JsonElement expected = isExcused ? expNs : c.GetProperty("expected");
        if (isExcused)
        {
            excused++;
            Console.WriteLine($"  excused {id}: {note}");
        }

        switch (kind)
        {
            case "activation":
            {
                NDArray x = ToNDArray(c.GetProperty("inputs").GetProperty("x"));
                BaseActivation act = MakeActivation(name);
                act.Forward(x);
                Assert(id, act.Output, expected);
                break;
            }
            case "activation_grad":
            {
                NDArray x = ToNDArray(c.GetProperty("inputs").GetProperty("x"));
                BaseActivation act = MakeActivation(name);
                act.Forward(x);
                act.Backward(np.ones(x.Shape, NPTypeCode.Single));
                Assert(id, act.InputGrad, expected);
                break;
            }
            case "loss":
            {
                var (cost, preds, labels) = MakeLossCall(name, c);
                NDArray loss = cost.Forward(preds, labels);
                AssertScalar(id, (float)loss, expected);
                break;
            }
            case "loss_grad":
            {
                var (cost, preds, labels) = MakeLossCall(name, c);
                cost.Forward(preds, labels);          // SCE caches softmax here
                NDArray grad = cost.Backward(preds, labels);
                Assert(id, grad, expected);
                break;
            }
            case "metric":
            {
                float actual = RunMetric(name, c);
                AssertScalar(id, actual, expected);
                break;
            }
            case "init_std":
            {
                var shapeDims = c.GetProperty("params").GetProperty("shape").EnumerateArray().Select(e => e.GetInt32()).ToArray();
                BaseInitializer init = BaseInitializer.Get(name);

                // Sample std has SE ≈ std/sqrt(2N) — 4.2% for the (3,3,4,8)
                // conv shape's 288 elements. Mirror the generator: average the
                // std over 5 seeded draws (SE/√5) so the 5% gate is ~2.7σ.
                float stdSum = 0f;
                float maxAbsAll = 0f;
                const int draws = 5;
                for (int s = 0; s < draws; s++)
                {
                    np.random.seed(1234 + s);
                    NDArray w = init.Initialize(new Shape(shapeDims));
                    stdSum += (float)np.std(w);
                    maxAbsAll = Math.Max(maxAbsAll, (float)np.max(np.abs(w)));
                }
                float std = stdSum / draws;
                float target = expected.GetSingle();
                Check(id + " std", Math.Abs(std - target) <= 0.05f * target, $"std={std} keras={target}");
                if (c.TryGetProperty("limit", out var lim))
                    Check(id + " limit", maxAbsAll <= lim.GetSingle() + 1e-6f, $"max={maxAbsAll} limit={lim.GetSingle()}");
                break;
            }
            // ---------------- normalization / embedding / regularizer layers ----------------
            case "dropout":
            {
                float rate = (float)c.GetProperty("params").GetProperty("rate").GetDouble();
                var exp = expected;
                float expScale = (float)exp.GetProperty("scale").GetDouble();

                var drop = new Dropout(rate);
                var ones = np.ones(new Shape(200, 20), NPTypeCode.Single);

                // Training: survivors carry EXACTLY the 1/(1-rate) scale.
                np.random.seed(20240726);
                drop.Training = true;
                drop.Forward(ones);
                var outFlat = np.reshape(drop.Output, new Shape((int)drop.Output.size));

                float seenScale = 0f;
                int kept = 0;
                bool onlyTwoValues = true;
                for (int i = 0; i < outFlat.size; i++)
                {
                    float v = outFlat.GetSingle(i);
                    if (v == 0f) continue;
                    kept++;
                    if (seenScale == 0f) seenScale = v;
                    else if (v != seenScale) onlyTwoValues = false;
                }

                if (rate == 0f)
                {
                    Check(id + " rate=0 is identity", kept == outFlat.size && seenScale == 1f,
                          $"kept={kept}/{outFlat.size} scale={seenScale}");
                }
                else
                {
                    Check(id + " support is {0, 1/(1-rate)}", onlyTwoValues, $"saw multiple nonzero values");
                    Check(id + " scale", FloatClose(seenScale, expScale), $"actual={seenScale} keras={expScale}");
                    // The mask is RNG-specific (MT19937 here, Keras's own there),
                    // so the KEPT FRACTION is checked statistically: 4000 draws
                    // give a standard error under 0.008, and 0.05 is >6 sigma.
                    float frac = (float)kept / outFlat.size;
                    Check(id + " kept fraction ~ 1-rate", Math.Abs(frac - (1f - rate)) < 0.05f,
                          $"kept={frac:F4} expected~{1f - rate:F4}");
                }

                // Backward must reuse the SAME scaled mask, so grad/output ratio
                // is constant wherever the output survived.
                drop.Backward(np.ones(ones.Shape, NPTypeCode.Single));
                var gFlat = np.reshape(drop.InputGrad, new Shape((int)drop.InputGrad.size));
                bool maskMatches = true;
                for (int i = 0; i < gFlat.size; i++)
                    if ((outFlat.GetSingle(i) == 0f) != (gFlat.GetSingle(i) == 0f))
                    { maskMatches = false; break; }
                Check(id + " backward reuses the forward mask", maskMatches);

                // Inference is the identity, whatever the rate.
                drop.Training = false;
                drop.Forward(ones);
                Check(id + " inference is identity",
                      exp.GetProperty("eval_is_identity").GetInt32() == 1 &&
                      (float)np.sum(np.abs(drop.Output - ones)) == 0f);
                break;
            }

            case "batchnorm":
            {
                var inputs = c.GetProperty("inputs");
                var p = c.GetProperty("params");
                bool training = p.GetProperty("training").GetBoolean();
                float momentum = (float)p.GetProperty("momentum").GetDouble();
                float epsilon = (float)p.GetProperty("epsilon").GetDouble();

                NDArray x = ToNDArrayND(inputs.GetProperty("x"));
                NDArray upstream = ToNDArrayND(inputs.GetProperty("upstream"));
                int features = (int)x.shape[1];

                var bn = new BatchNormalization(features, momentum, epsilon);
                bn.Parameters["gamma"] = ToNDArrayND(inputs.GetProperty("gamma"));
                bn.Parameters["beta"] = ToNDArrayND(inputs.GetProperty("beta"));
                bn.NonTrainable["moving_mean"] = ToNDArrayND(inputs.GetProperty("moving_mean"));
                bn.NonTrainable["moving_variance"] = ToNDArrayND(inputs.GetProperty("moving_variance"));

                bn.Training = training;
                bn.Forward(x);
                Assert(id + " y", bn.Output, expected.GetProperty("y"));
                Assert(id + " moving_mean", bn.NonTrainable["moving_mean"], expected.GetProperty("moving_mean_out"));
                Assert(id + " moving_variance", bn.NonTrainable["moving_variance"], expected.GetProperty("moving_variance_out"));

                bn.Backward(upstream);
                Assert(id + " dx", bn.InputGrad, expected.GetProperty("dx"));
                Assert(id + " dgamma", bn.Grads["gamma"], expected.GetProperty("dgamma"));
                Assert(id + " dbeta", bn.Grads["beta"], expected.GetProperty("dbeta"));
                break;
            }

            case "layernorm":
            {
                var inputs = c.GetProperty("inputs");
                float epsilon = (float)c.GetProperty("params").GetProperty("epsilon").GetDouble();

                NDArray x = ToNDArrayND(inputs.GetProperty("x"));
                NDArray upstream = ToNDArrayND(inputs.GetProperty("upstream"));

                var ln = new LayerNormalization((int)x.shape[1], epsilon);
                ln.Parameters["gamma"] = ToNDArrayND(inputs.GetProperty("gamma"));
                ln.Parameters["beta"] = ToNDArrayND(inputs.GetProperty("beta"));

                ln.Forward(x);
                Assert(id + " y", ln.Output, expected.GetProperty("y"));

                ln.Backward(upstream);
                Assert(id + " dx", ln.InputGrad, expected.GetProperty("dx"));
                Assert(id + " dgamma", ln.Grads["gamma"], expected.GetProperty("dgamma"));
                Assert(id + " dbeta", ln.Grads["beta"], expected.GetProperty("dbeta"));
                break;
            }

            case "embedding":
            {
                var inputs = c.GetProperty("inputs");
                NDArray w = ToNDArrayND(inputs.GetProperty("w"));
                NDArray idx = ToIntNDArray(inputs.GetProperty("indices"));
                NDArray upstream = ToNDArrayND(inputs.GetProperty("upstream"));

                var emb = new Embedding((int)w.shape[0], (int)w.shape[1]);
                emb.Parameters["w"] = w;

                emb.Forward(idx);
                Assert(id + " y", emb.Output, expected.GetProperty("y"));

                emb.Backward(upstream);
                Assert(id + " dw (scatter-ADD)", emb.Grads["w"], expected.GetProperty("dw"));
                Check(id + " InputGrad is null (indices aren't differentiable)", emb.InputGrad is null);
                break;
            }

            case "regularizer":
            {
                var p = c.GetProperty("params");
                NDArray w = ToNDArrayND(c.GetProperty("inputs").GetProperty("w"));
                BaseRegularizer reg = name switch
                {
                    "l1" => new L1((float)p.GetProperty("l1").GetDouble()),
                    "l2" => new L2((float)p.GetProperty("l2").GetDouble()),
                    "l1l2" => new L1L2((float)p.GetProperty("l1").GetDouble(), (float)p.GetProperty("l2").GetDouble()),
                    _ => throw new ArgumentException($"unknown regularizer {name}"),
                };
                AssertScalar(id + " penalty", reg.Penalty(w), expected.GetProperty("penalty"));
                Assert(id + " gradient", reg.Gradient(w), expected.GetProperty("grad"));
                break;
            }

            default:
                Check(id, false, $"unknown kind '{kind}'");
                break;
        }
    }
    catch (Exception ex)
    {
        Check(id, false, $"threw {ex.GetType().Name}: {ex.Message}");
    }
}

Console.WriteLine();
Console.WriteLine($"RESULT: {pass} passed, {fail} failed, {excused} excused-documented divergences");
return fail == 0 ? 0 : 1;

// ======================================================================

void Check(string name, bool ok, string detail = "")
{
    if (ok) pass++;
    else { fail++; Console.WriteLine($"  FAIL {name} {detail}"); }
}

void Assert(string name, NDArray actual, JsonElement expected)
{
    float[] exp = Flatten(expected).ToArray();
    var flat = np.reshape(actual, new Shape((int)actual.size)).astype(NPTypeCode.Single);
    if (flat.size != exp.Length)
    { Check(name, false, $"size {flat.size} != {exp.Length}"); return; }
    for (int i = 0; i < exp.Length; i++)
    {
        if (!FloatClose(flat.GetSingle(i), exp[i]))
        { Check(name, false, $"[{i}] actual={flat.GetSingle(i)} expected={exp[i]}"); return; }
    }
    Check(name, true);
}

void AssertScalar(string name, float actual, JsonElement expected)
{
    float exp = expected.ValueKind == JsonValueKind.String ? ParseSentinel(expected.GetString()) : (float)expected.GetDouble();
    Check(name, FloatClose(actual, exp), $"actual={actual} expected={exp}");
}

bool FloatClose(float a, float b)
{
    if (float.IsNaN(a) || float.IsNaN(b)) return float.IsNaN(a) && float.IsNaN(b);
    if (float.IsInfinity(a) || float.IsInfinity(b)) return a == b;
    float diff = Math.Abs(a - b);
    return diff <= AbsTol || diff <= RelTol * Math.Max(Math.Abs(a), Math.Abs(b));
}

static float ParseSentinel(string s) => s switch
{
    "NaN" => float.NaN,
    "Infinity" => float.PositiveInfinity,
    "-Infinity" => float.NegativeInfinity,
    _ => float.Parse(s),
};

static IEnumerable<float> Flatten(JsonElement e)
{
    switch (e.ValueKind)
    {
        case JsonValueKind.Array:
            foreach (var child in e.EnumerateArray())
                foreach (var v in Flatten(child))
                    yield return v;
            break;
        case JsonValueKind.String:
            yield return ParseSentinel(e.GetString());
            break;
        default:
            yield return (float)e.GetDouble();
            break;
    }
}

static NDArray ToNDArray(JsonElement e)
{
    // 1-D or 2-D float32 from (possibly nested) JSON arrays with sentinels.
    var first = e.EnumerateArray().First();
    if (first.ValueKind == JsonValueKind.Array)
    {
        int rows = e.GetArrayLength(), cols = first.GetArrayLength();
        var nd = np.zeros(new Shape(rows, cols), NPTypeCode.Single);
        int i = 0;
        foreach (var row in e.EnumerateArray())
        {
            int j = 0;
            foreach (var v in row.EnumerateArray())
            {
                nd[$"{i}:{i + 1}"][$":, {j}:{j + 1}"] = (NDArray)ReadFloat(v);
                j++;
            }
            i++;
        }
        return nd;
    }
    float[] vals = e.EnumerateArray().Select(ReadFloat).ToArray();
    return np.array(vals);
}

static float ReadFloat(JsonElement v)
    => v.ValueKind == JsonValueKind.String ? ParseSentinel(v.GetString()) : (float)v.GetDouble();

/// <summary>Shape of an arbitrarily-nested JSON array (first element per level).</summary>
static int[] NestedShape(JsonElement e)
{
    var dims = new List<int>();
    JsonElement cur = e;
    while (cur.ValueKind == JsonValueKind.Array)
    {
        int len = cur.GetArrayLength();
        dims.Add(len);
        if (len == 0) break;
        cur = cur.EnumerateArray().First();
    }
    return dims.ToArray();
}

/// <summary>
/// N-dimensional float32 reader — the layer cases need 3-D (sequence embeddings)
/// where the original ToNDArray only handled 1-D and 2-D.
/// </summary>
static NDArray ToNDArrayND(JsonElement e)
{
    float[] flat = Flatten(e).ToArray();
    int[] dims = NestedShape(e);
    NDArray nd = np.array(flat);
    return dims.Length <= 1 ? nd : np.reshape(nd, new Shape(dims));
}

/// <summary>N-dimensional int32 reader (embedding indices).</summary>
static NDArray ToIntNDArray(JsonElement e)
{
    int[] flat = Flatten(e).Select(v => (int)v).ToArray();
    int[] dims = NestedShape(e);
    NDArray nd = np.array(flat);
    return dims.Length <= 1 ? nd : np.reshape(nd, new Shape(dims));
}

static int[] ToIntArray(JsonElement e) => e.EnumerateArray().Select(x => x.GetInt32()).ToArray();

static BaseActivation MakeActivation(string name) => name switch
{
    "relu" => new ReLU(),
    "sigmoid" => new Sigmoid(),
    "tanh" => new Tanh(),
    "leaky_relu" => new LeakyReLU(0.3f),
    "elu" => new ELU(1.0f),
    "gelu" => new GELU(),
    "silu" => new SiLU(),
    "softplus" => new Softplus(),
    "selu" => new SELU(),
    "softmax" => new Softmax(),
    _ => throw new ArgumentException($"unknown activation {name}"),
};

static (BaseCost cost, NDArray preds, NDArray labels) MakeLossCall(string name, JsonElement c)
{
    var inputs = c.GetProperty("inputs");
    switch (name)
    {
        case "cce":
            return (new CategoricalCrossentropy(), ToNDArray(inputs.GetProperty("y_pred")), ToNDArray(inputs.GetProperty("y_true")));
        case "scce":
            return (new SparseCategoricalCrossentropy(), ToNDArray(inputs.GetProperty("y_pred")), np.array(ToIntArray(inputs.GetProperty("labels"))));
        case "bce":
            return (new BinaryCrossEntropy(), ToNDArray(inputs.GetProperty("y_pred")), ToNDArray(inputs.GetProperty("y_true")));
        case "huber":
        {
            float delta = (float)c.GetProperty("params").GetProperty("delta").GetDouble();
            return (new Huber(delta), ToNDArray(inputs.GetProperty("y_pred")), ToNDArray(inputs.GetProperty("y_true")));
        }
        case "hinge":
            return (new Hinge(), ToNDArray(inputs.GetProperty("y_pred")), ToNDArray(inputs.GetProperty("y_true")));
        case "kl":
            return (new KLDivergence(), ToNDArray(inputs.GetProperty("y_pred")), ToNDArray(inputs.GetProperty("y_true")));
        case "logcosh":
            return (new LogCosh(), ToNDArray(inputs.GetProperty("y_pred")), ToNDArray(inputs.GetProperty("y_true")));
        case "sce_logits":
            return (new SoftmaxCrossEntropy(), ToNDArray(inputs.GetProperty("logits")), ToNDArray(inputs.GetProperty("y_true")));
        default:
            throw new ArgumentException($"unknown loss {name}");
    }
}

float RunMetric(string name, JsonElement c)
{
    var inputs = c.GetProperty("inputs");
    NDArray yt = ToNDArray(inputs.GetProperty("y_true"));
    NDArray yp = ToNDArray(inputs.GetProperty("y_pred"));
    return name switch
    {
        "precision" => (float)new Precision(0.5f).Calculate(yp, yt),
        "recall" => (float)new Recall(0.5f).Calculate(yp, yt),
        "binary_accuracy" => (float)new BinaryAccuracy().Calculate(yp, yt),
        "top_k" => (float)new TopKCategoricalAccuracy(c.GetProperty("params").GetProperty("k").GetInt32()).Calculate(yp, yt),
        "f1_binary" => (float)new F1Score(F1Average.Binary, 0.5f).Calculate(yp, yt),
        "f1_macro" => (float)new F1Score(F1Average.Macro).Calculate(yp, yt),
        "r2" => (float)new R2Score().Calculate(yp, yt),
        "rmse" => (float)new RootMeanSquaredError().Calculate(yp, yt),
        "accuracy" => (float)new Accuracy().Calculate(yp, yt),
        _ => throw new ArgumentException($"unknown metric {name}"),
    };
}
