using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Numerics;
using System.Reflection;
using System.Text.Json;

namespace NumSharp.Tests.Fuzz.RandomApi
{
    /// <summary>
    ///     Replays one random-API corpus case (op <c>random_api</c>, generated by <c>test/oracle/gen_random_oracle.py</c>):
    ///     builds the receiver the case describes, primes it, decodes the typed arguments against the EXACT overload the
    ///     case names (resolved by its canonical signature, <see cref="RandomApiSurface.Resolve"/>) and invokes that member.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///     Invoking by reflection is the point: a hand-written dispatch picks an overload at compile time and can quietly
    ///     test a different one than it claims, while here the case's signature IS the member that runs. An omitted optional
    ///     argument receives the parameter's declared default, exactly the constant the C# compiler would emit for a call
    ///     that leaves it out; the generator calls NumPy without it, so a C# default that differs from NumPy's shows as a
    ///     divergence.
    ///     </para>
    ///     <para>
    ///     Every mirror of a Python-side construct lives here: receivers (<c>recv</c>), priming (<c>prime</c>) and argument
    ///     encodings (<c>args</c>). The two sides must stay in lockstep; a spelling this decoder does not know fails the
    ///     case loudly (<see cref="NotSupportedException"/>) rather than guessing.
    ///     </para>
    /// </remarks>
    internal static class RandomApiHarness
    {
        /// <summary>The outcome of one invocation.</summary>
        /// <param name="Result">The member's return value (null for <c>void</c>, setters and fields' absence).</param>
        /// <param name="Receiver">The receiver after the call (null for constructors and static members).</param>
        /// <param name="Member">The resolved member.</param>
        internal readonly record struct Outcome(object Result, object Receiver, RandomApiSurface.Member Member);

        /// <summary>
        ///     Runs a case: receiver, priming, the call (repeated <c>calls</c> times; the last result is the observed one).
        /// </summary>
        /// <param name="p">The case params (<c>sig</c>, <c>recv</c>, <c>prime</c>, <c>args</c>, <c>calls</c>, <c>targs</c>).</param>
        /// <param name="operands">The reconstructed NDArray operands the arguments reference by index.</param>
        /// <returns>The last result, the receiver and the member.</returns>
        /// <exception cref="Exception">Whatever the member throws, unwrapped from reflection's
        ///     <see cref="TargetInvocationException"/> — the error-parity check compares it against NumPy's.</exception>
        /// <exception cref="NotSupportedException">The case uses a receiver, priming or argument spelling this harness does
        ///     not know (a generator/harness mismatch, never a NumSharp result).</exception>
        internal static Outcome Run(IReadOnlyDictionary<string, JsonElement> p, NDArray[] operands)
        {
            var member = RandomApiSurface.Resolve(p["sig"].GetString());
            object receiver = BuildReceiver(p["recv"]);
            Prime(receiver, p.TryGetValue("prime", out var pr) ? pr.GetString() : "none");
            int calls = p.TryGetValue("calls", out var c) ? c.GetInt32() : 1;

            object result = null;
            for (int k = 0; k < calls; k++)
            {
                // A superseded result of a repeated call is harness scaffolding: dispose it so the leak gates do not
                // count it as a library escape (the draws>1 pattern of the other random tiers).
                if (k > 0 && result is NDArray previous)
                    previous.Dispose();
                result = Invoke(member, receiver, p, operands);
            }
            return new Outcome(result, receiver, member);
        }

        /// <summary>Invokes the resolved member once with the case's decoded arguments.</summary>
        /// <param name="member">The resolved member.</param>
        /// <param name="receiver">The receiver (null for constructors, static members and operators).</param>
        /// <param name="p">The case params.</param>
        /// <param name="operands">The NDArray operands.</param>
        /// <returns>The member's result (null for void methods and setters).</returns>
        /// <exception cref="Exception">The member's own exception, unwrapped.</exception>
        private static object Invoke(RandomApiSurface.Member member, object receiver, IReadOnlyDictionary<string, JsonElement> p,
            NDArray[] operands)
        {
            try
            {
                switch (member.Info)
                {
                    case ConstructorInfo ctor:
                        return ctor.Invoke(DecodeArgs(ctor.GetParameters(), p, operands));
                    case MethodInfo method:
                    {
                        var m = method;
                        if (m.IsGenericMethodDefinition)
                        {
                            var targs = new List<Type>();
                            foreach (var t in p["targs"].EnumerateArray())
                                targs.Add(ClrType(t.GetString()));
                            m = m.MakeGenericMethod(targs.ToArray());
                        }
                        return m.Invoke(m.IsStatic ? null : receiver, DecodeArgs(m.GetParameters(), p, operands));
                    }
                    case PropertyInfo prop when member.Kind == "get":
                        return prop.GetValue(receiver);
                    case PropertyInfo prop:
                        prop.SetValue(receiver, DecodeArgs(prop.SetMethod!.GetParameters(), p, operands)[0]);
                        return null;
                    case FieldInfo field:
                        return field.GetValue(field.IsStatic ? null : receiver);
                    default:
                        throw new NotSupportedException($"{member.Sig}: unsupported member kind {member.Info?.GetType().Name}");
                }
            }
            catch (TargetInvocationException tie) when (tie.InnerException != null)
            {
                System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(tie.InnerException).Throw();
                throw; // unreachable
            }
        }

        // ---------------------------------------------------------------------------------------------------------------
        // Receivers and priming
        // ---------------------------------------------------------------------------------------------------------------

        /// <summary>
        ///     Builds the receiver a case describes, mirroring <c>Recv.build</c> in the generator: the legacy-seeded
        ///     <c>RandomState(seed)</c> or <c>RandomState(ENGINE(seed))</c>, <c>Generator(ENGINE(seed))</c>, a bare
        ///     <c>ENGINE(seed)</c>, or none.
        /// </summary>
        /// <param name="spec">The <c>recv</c> object.</param>
        /// <returns>The receiver, or null for <c>none</c>.</returns>
        /// <exception cref="NotSupportedException">An unknown receiver kind.</exception>
        internal static object BuildReceiver(JsonElement spec)
        {
            string kind = spec.GetProperty("k").GetString();
            string engine = spec.TryGetProperty("engine", out var e) ? e.GetString() : null;
            string seedText = spec.TryGetProperty("seed", out var s) ? s.GetString() : null;
            switch (kind)
            {
                case "none":
                    return null;
                case "RandomState":
                {
                    long seed = long.Parse(seedText, CultureInfo.InvariantCulture);
                    return engine == null ? np.random.RandomState(seed) : np.random.RandomState(MakeEngine(engine, seed));
                }
                case "Generator":
                    return new Generator(MakeEngine(engine, long.Parse(seedText, CultureInfo.InvariantCulture)));
                case "BitGenerator":
                    return MakeEngine(engine, long.Parse(seedText, CultureInfo.InvariantCulture));
                // State objects of an inner stream receiver (`of`, primed by its own `prime`): the legacy tuple
                // (NumPy's get_state() tuple; a boxed struct here) and the dict form (get_state(legacy=False)).
                case "legacy_tuple":
                    return InnerRandomState(spec.GetProperty("of")).get_state();
                case "rs_dict":
                    return InnerRandomState(spec.GetProperty("of")).get_state(false);
                default:
                    throw new NotSupportedException($"unknown receiver kind '{kind}'");
            }
        }

        /// <summary>
        ///     Builds and primes the RandomState an inner receiver spec describes (the spec carries its own <c>prime</c>):
        ///     the source of a state-object receiver or argument.
        /// </summary>
        /// <param name="spec">A <c>RandomState</c> receiver spec with <c>prime</c>.</param>
        /// <returns>The primed RandomState.</returns>
        /// <exception cref="NotSupportedException">The spec is not a RandomState receiver.</exception>
        private static NumPyRandom InnerRandomState(JsonElement spec)
        {
            var inner = BuildReceiver(spec) as NumPyRandom
                        ?? throw new NotSupportedException("a state object's source must be a RandomState receiver");
            Prime(inner, spec.TryGetProperty("prime", out var pr) ? pr.GetString() : "none");
            return inner;
        }

        /// <summary>
        ///     Builds and primes the bit generator an argument spec describes (<c>engine</c>, <c>seed</c>, <c>prime</c>) —
        ///     the generator's <c>bitgen_obj</c> / <c>bgstate_obj</c>.
        /// </summary>
        /// <param name="spec">The spec.</param>
        /// <returns>The primed engine.</returns>
        private static BitGenerator PrimedEngine(JsonElement spec)
        {
            var bg = MakeEngine(spec.GetProperty("engine").GetString(),
                long.Parse(spec.GetProperty("seed").GetString(), CultureInfo.InvariantCulture));
            Prime(bg, spec.GetProperty("prime").GetString());
            return bg;
        }

        /// <summary>
        ///     Decodes an object argument (<c>{"obj": {kind: spec}}</c>) — the generator's <c>Obj</c> encodings: a bit
        ///     generator, a bit generator's state, a legacy state tuple (another receiver's or spelled out), a RandomState
        ///     dict state (another receiver's or from parts), a Python int or str for an <c>object</c> parameter.
        /// </summary>
        /// <param name="obj">The object spec (exactly one property).</param>
        /// <returns>The decoded value (a boxed <see cref="NativeRandomState"/> for the tuple forms).</returns>
        /// <exception cref="NotSupportedException">An unknown object kind.</exception>
        private static object DecodeObject(JsonElement obj)
        {
            var prop = obj.EnumerateObject().Single();
            var s = prop.Value;
            switch (prop.Name)
            {
                case "bitgen":
                    return PrimedEngine(s);
                case "bgstate":
                    return PrimedEngine(s).state;
                case "legacy_state_of":
                    return InnerRandomState(s).get_state();
                case "legacy_state":
                {
                    var keyEl = s.GetProperty("key");
                    uint[] key = keyEl.ValueKind == JsonValueKind.Null
                        ? null
                        : Array.ConvertAll(StringArray(keyEl), x => uint.Parse(x, CultureInfo.InvariantCulture));
                    var t = new NativeRandomState(key, int.Parse(s.GetProperty("pos").GetString(), CultureInfo.InvariantCulture),
                        int.Parse(s.GetProperty("has_gauss").GetString(), CultureInfo.InvariantCulture),
                        BitConverter.Int64BitsToDouble(unchecked((long)ulong.Parse(s.GetProperty("gauss").GetString(), NumberStyles.HexNumber))));
                    // The algorithm name is a plain field of the tuple (NumPy's element 0), set after construction so
                    // a non-MT19937 name reaches set_state's own check.
                    t.Algorithm = s.GetProperty("algorithm").GetString();
                    return t;
                }
                case "rs_dict_of":
                    return InnerRandomState(s).get_state(false);
                case "rs_dict_parts":
                {
                    var stateEl = s.GetProperty("state");
                    BitGeneratorState state = stateEl.ValueKind == JsonValueKind.Null ? null : PrimedEngine(stateEl).state;
                    return new NumPyRandom.State(state, int.Parse(s.GetProperty("has_gauss").GetString(), CultureInfo.InvariantCulture),
                        BitConverter.Int64BitsToDouble(unchecked((long)ulong.Parse(s.GetProperty("gauss").GetString(), NumberStyles.HexNumber))));
                }
                case "pyint":
                {
                    // A Python int: a boxed long when it fits (what C# code would pass), else the BigInteger.
                    var big = BigInteger.Parse(s.GetString(), CultureInfo.InvariantCulture);
                    return big >= long.MinValue && big <= long.MaxValue ? (object)(long)big : big;
                }
                case "str":
                    return s.GetString();
                default:
                    throw new NotSupportedException($"unknown object argument kind '{prop.Name}'");
            }
        }

        /// <summary><c>ENGINE(seed)</c>: a non-negative integer seed through <see cref="SeedSequence"/>, as NumPy's
        ///     <c>np.random.ENGINE(int)</c> does.</summary>
        /// <param name="engine">The engine name (<c>MT19937</c>, <c>PCG64</c>, <c>PCG64DXSM</c>, <c>Philox</c>, <c>SFC64</c>).</param>
        /// <param name="seed">The seed.</param>
        /// <returns>The bit generator.</returns>
        /// <exception cref="NotSupportedException">An unknown engine name.</exception>
        internal static BitGenerator MakeEngine(string engine, long seed) => engine switch
        {
            "MT19937" => new MT19937(seed),
            "PCG64" => new PCG64(seed),
            "PCG64DXSM" => new PCG64DXSM(seed),
            "Philox" => new Philox(seed),
            "SFC64" => new SFC64(seed),
            _ => throw new NotSupportedException($"unknown engine '{engine}'"),
        };

        /// <summary>
        ///     Primes a receiver exactly as the generator's <c>prime</c> does: <c>raw3</c> three raw words, <c>u32</c> one
        ///     full-range uint32 draw (a buffered half on a 64-bit engine), <c>gauss</c> one legacy normal (the cache full).
        /// </summary>
        /// <param name="receiver">The receiver.</param>
        /// <param name="how">The priming name.</param>
        /// <exception cref="NotSupportedException">An unknown priming, or one that does not apply to the receiver.</exception>
        internal static void Prime(object receiver, string how)
        {
            if (how == "none")
                return;
            NDArray scratch;
            switch (how)
            {
                case "raw3":
                {
                    var bg = receiver switch
                    {
                        BitGenerator b => b,
                        Generator g => g.bit_generator,
                        NumPyRandom rs => rs._bit_generator,
                        _ => throw new NotSupportedException($"raw3 priming on {receiver?.GetType().Name}"),
                    };
                    scratch = bg.random_raw(new Shape(3));
                    break;
                }
                case "u32":
                    scratch = receiver switch
                    {
                        Generator g => g.integers(0L, 4294967296L, new Shape(1), np.uint32),
                        NumPyRandom rs => rs.randint(0L, 4294967296L, new Shape(1), np.uint32),
                        _ => throw new NotSupportedException($"u32 priming on {receiver?.GetType().Name}"),
                    };
                    break;
                case "gauss":
                    scratch = receiver is NumPyRandom r
                        ? r.standard_normal()
                        : throw new NotSupportedException($"gauss priming on {receiver?.GetType().Name}");
                    break;
                default:
                    throw new NotSupportedException($"unknown priming '{how}'");
            }
            scratch.Dispose();
        }

        // ---------------------------------------------------------------------------------------------------------------
        // Arguments
        // ---------------------------------------------------------------------------------------------------------------

        /// <summary>
        ///     Decodes the case's arguments against a member's parameters, by NAME (the generator writes every parameter of
        ///     the overload, in order; an omitted one carries <c>omit</c>).
        /// </summary>
        /// <param name="parameters">The resolved member's parameters.</param>
        /// <param name="p">The case params (its <c>args</c> array).</param>
        /// <param name="operands">The NDArray operands.</param>
        /// <returns>The argument vector, defaults substituted for omitted parameters.</returns>
        /// <exception cref="InvalidOperationException">The case's arguments do not name the member's parameters in order —
        ///     a generator/inventory mismatch.</exception>
        private static object[] DecodeArgs(ParameterInfo[] parameters, IReadOnlyDictionary<string, JsonElement> p, NDArray[] operands)
        {
            var args = p["args"];
            if (args.GetArrayLength() != parameters.Length)
                throw new InvalidOperationException(
                    $"{p["sig"].GetString()}: the case carries {args.GetArrayLength()} arguments for {parameters.Length} parameters");
            var values = new object[parameters.Length];
            int i = 0;
            foreach (var a in args.EnumerateArray())
            {
                var param = parameters[i];
                string name = a.GetProperty("n").GetString();
                if (name != param.Name)
                    throw new InvalidOperationException($"{p["sig"].GetString()}: argument {i} is '{name}', the parameter is '{param.Name}'");
                values[i] = a.TryGetProperty("omit", out _) ? DefaultOf(param) : Decode(a, param.ParameterType, operands);
                i++;
            }
            return values;
        }

        /// <summary>
        ///     The value the compiler passes for an omitted optional parameter: its declared default, or <c>default(T)</c> for a
        ///     struct whose default reflection reports as null (<c>Shape size = default</c>).
        /// </summary>
        /// <param name="param">An optional parameter.</param>
        /// <returns>The default value.</returns>
        /// <exception cref="InvalidOperationException">The parameter is not optional (a case omitted a required argument).</exception>
        private static object DefaultOf(ParameterInfo param)
        {
            if (!param.HasDefaultValue)
                throw new InvalidOperationException($"parameter '{param.Name}' is required but the case omits it");
            object d = param.DefaultValue;
            var t = param.ParameterType;
            // `default(T)` for a struct is the all-zero value, NOT `new T()`: Activator.CreateInstance runs a declared
            // parameterless constructor, and Shape's builds Shape.Scalar (size=()) where the compiler passes
            // default(Shape) (size=None). An uninitialized object is exactly the zeroed struct.
            if (d == null && t.IsValueType && Nullable.GetUnderlyingType(t) == null)
                return System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(t);
            return d;
        }

        /// <summary>
        ///     Decodes one argument to the parameter's CLR type. See <c>encode</c> in the generator for the spellings:
        ///     doubles by IEEE bits, integers as decimal strings, <c>Shape</c> as dims or <c>none</c>, <c>DType</c> by name,
        ///     NDArrays by operand index, arrays element-wise, <c>null</c> for a null reference.
        /// </summary>
        /// <param name="a">The argument object.</param>
        /// <param name="t">The parameter type.</param>
        /// <param name="operands">The NDArray operands.</param>
        /// <returns>The decoded value.</returns>
        /// <exception cref="NotSupportedException">A parameter type or spelling the harness does not decode.</exception>
        internal static object Decode(JsonElement a, Type t, NDArray[] operands)
        {
            if (a.TryGetProperty("null", out _))
                return null;
            if (a.TryGetProperty("obj", out var obj))
                return DecodeObject(obj);
            var under = Nullable.GetUnderlyingType(t) ?? t;
            if (under == typeof(double))
                return BitConverter.Int64BitsToDouble(unchecked((long)ulong.Parse(a.GetProperty("bits").GetString(), NumberStyles.HexNumber)));
            if (under == typeof(float))
                return (float)BitConverter.Int64BitsToDouble(unchecked((long)ulong.Parse(a.GetProperty("bits").GetString(), NumberStyles.HexNumber)));
            if (under == typeof(int))
                return int.Parse(a.GetProperty("v").GetString(), CultureInfo.InvariantCulture);
            if (under == typeof(long))
                return long.Parse(a.GetProperty("v").GetString(), CultureInfo.InvariantCulture);
            if (under == typeof(uint))
                return uint.Parse(a.GetProperty("v").GetString(), CultureInfo.InvariantCulture);
            if (under == typeof(ulong))
                return ulong.Parse(a.GetProperty("v").GetString(), CultureInfo.InvariantCulture);
            if (under == typeof(BigInteger))
                return BigInteger.Parse(a.GetProperty("v").GetString(), CultureInfo.InvariantCulture);
            if (under == typeof(UInt128))
                return UInt128.Parse(a.GetProperty("v").GetString(), CultureInfo.InvariantCulture);
            if (under == typeof(bool))
                return a.GetProperty("v").GetBoolean();
            if (under == typeof(string))
                return a.GetProperty("v").GetString();
            if (under == typeof(Shape))
            {
                if (a.TryGetProperty("none", out _))
                    return default(Shape);
                var dims = LongArray(a.GetProperty("dims"));
                return dims.Length == 0 ? Shape.Scalar : new Shape(dims);
            }
            if (under == typeof(DType))
                return np.dtype(a.GetProperty("name").GetString());
            if (typeof(NDArray).IsAssignableFrom(under))
                return operands[a.GetProperty("op").GetInt32()];
            if (under == typeof(long[]))
                return LongArray(a.GetProperty("v"));
            if (under == typeof(int[]))
                return Array.ConvertAll(LongArray(a.GetProperty("v")), x => checked((int)x));
            if (under == typeof(uint[]))
                return Array.ConvertAll(StringArray(a.GetProperty("v")), x => uint.Parse(x, CultureInfo.InvariantCulture));
            if (under == typeof(ulong[]))
                return Array.ConvertAll(StringArray(a.GetProperty("v")), x => ulong.Parse(x, CultureInfo.InvariantCulture));
            if (under == typeof(double[]))
                return Array.ConvertAll(StringArray(a.GetProperty("v")),
                    x => BitConverter.Int64BitsToDouble(unchecked((long)ulong.Parse(x, NumberStyles.HexNumber))));
            if (under == typeof(double[,]))
            {
                var rows = a.GetProperty("rows");
                int r = rows.GetArrayLength(), cols = r == 0 ? 0 : rows[0].GetArrayLength();
                var m = new double[r, cols];
                for (int i = 0; i < r; i++)
                    for (int j = 0; j < cols; j++)
                        m[i, j] = BitConverter.Int64BitsToDouble(unchecked((long)ulong.Parse(rows[i][j].GetString(), NumberStyles.HexNumber)));
                return m;
            }
            throw new NotSupportedException($"the random-API harness does not decode arguments of type {RandomApiSurface.TypeName(t)}");
        }

        /// <summary>A JSON array of decimal strings as <see cref="long"/>s.</summary>
        /// <param name="e">The array.</param>
        /// <returns>The values.</returns>
        private static long[] LongArray(JsonElement e)
            => Array.ConvertAll(StringArray(e), x => long.Parse(x, CultureInfo.InvariantCulture));

        /// <summary>A JSON array of strings.</summary>
        /// <param name="e">The array.</param>
        /// <returns>The strings.</returns>
        private static string[] StringArray(JsonElement e)
        {
            var list = new string[e.GetArrayLength()];
            int i = 0;
            foreach (var x in e.EnumerateArray())
                list[i++] = x.ValueKind == JsonValueKind.String ? x.GetString() : x.GetRawText();
            return list;
        }

        /// <summary>A generic type argument by its canonical name (<c>double</c>, <c>float</c>, <c>Half</c>, …).</summary>
        /// <param name="name">The canonical name.</param>
        /// <returns>The CLR type.</returns>
        /// <exception cref="NotSupportedException">An unknown name.</exception>
        internal static Type ClrType(string name) => name switch
        {
            "bool" => typeof(bool), "byte" => typeof(byte), "sbyte" => typeof(sbyte), "short" => typeof(short),
            "ushort" => typeof(ushort), "int" => typeof(int), "uint" => typeof(uint), "long" => typeof(long),
            "ulong" => typeof(ulong), "char" => typeof(char), "Half" => typeof(Half), "float" => typeof(float),
            "double" => typeof(double), "decimal" => typeof(decimal), "Complex" => typeof(Complex),
            _ => throw new NotSupportedException($"unknown type argument '{name}'"),
        };
    }
}
