using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using NumSharp;
using NumSharp.Backends.Iteration;

namespace NumSharp.UnitTest.Backends.Iterators
{
    /// <summary>
    /// Battle tests verifying NumSharp NpyIter produces EXACT same results as NumPy nditer.
    /// Each test includes the expected NumPy output in comments for verification.
    ///
    /// These tests were generated by running actual NumPy code and comparing results.
    /// </summary>
    [TestClass]
    public class NpyIterNumPyBattleTests
    {
        // =====================================================================
        // Test 1: Basic C-order iteration
        // NumPy: [0, 1, 2, 3, 4, 5]
        // =====================================================================
        [TestMethod]
        public void Battle_BasicCOrderIteration()
        {
            // NumPy:
            // arr = np.arange(6).reshape(2, 3)
            // with np.nditer(arr) as it:
            //     for x in it: values.append(int(x))
            // Result: [0, 1, 2, 3, 4, 5]

            var arr = np.arange(6).reshape(2, 3);
            var expected = new[] { 0, 1, 2, 3, 4, 5 };

            using var iter = NpyIterRef.New(arr);
            var values = new List<int>();

            do
            {
                values.Add(iter.GetValue<int>(0));
            } while (iter.Iternext());

            CollectionAssert.AreEqual(expected, values.ToArray(),
                "C-order iteration must match NumPy exactly");
        }

        // =====================================================================
        // Test 2: F-order iteration
        // NumPy: [0, 3, 1, 4, 2, 5]
        // =====================================================================
        [TestMethod]
        public void Battle_FOrderIteration()
        {
            // NumPy:
            // arr = np.arange(6).reshape(2, 3)
            // with np.nditer(arr, order='F') as it:
            //     for x in it: values.append(int(x))
            // Result: [0, 3, 1, 4, 2, 5]

            var arr = np.arange(6).reshape(2, 3);
            var expected = new[] { 0, 3, 1, 4, 2, 5 };

            using var iter = NpyIterRef.New(arr, order: NPY_ORDER.NPY_FORTRANORDER);
            var values = new List<int>();

            do
            {
                values.Add(iter.GetValue<int>(0));
            } while (iter.Iternext());

            CollectionAssert.AreEqual(expected, values.ToArray(),
                "F-order iteration must match NumPy exactly");
        }

        // =====================================================================
        // Test 3: Multi-operand iteration with broadcasting
        // NumPy: [(0, 0), (1, 1), (2, 2), (0, 3), (1, 4), (2, 5)]
        // =====================================================================
        [TestMethod]
        public void Battle_MultiOperandBroadcasting()
        {
            // NumPy:
            // a = np.arange(3)
            // b = np.arange(6).reshape(2, 3)
            // with np.nditer([a, b]) as it:
            //     for x, y in it: pairs.append((int(x), int(y)))
            // Result: [(0, 0), (1, 1), (2, 2), (0, 3), (1, 4), (2, 5)]

            var a = np.arange(3);
            var b = np.arange(6).reshape(2, 3);
            var expected = new[] { (0, 0), (1, 1), (2, 2), (0, 3), (1, 4), (2, 5) };

            using var iter = NpyIterRef.MultiNew(
                2, new[] { a, b },
                NpyIterGlobalFlags.None,
                NPY_ORDER.NPY_KEEPORDER,
                NPY_CASTING.NPY_NO_CASTING,
                new[] { NpyIterPerOpFlags.READONLY, NpyIterPerOpFlags.READONLY });

            var pairs = new List<(int, int)>();

            do
            {
                pairs.Add((iter.GetValue<int>(0), iter.GetValue<int>(1)));
            } while (iter.Iternext());

            CollectionAssert.AreEqual(expected, pairs.ToArray(),
                "Multi-operand broadcasting must match NumPy exactly");
        }

        // =====================================================================
        // Test 4: Sliced array iteration
        // NumPy: [4, 6, 8, 10]
        // =====================================================================
        [TestMethod]
        public void Battle_SlicedArrayIteration()
        {
            // NumPy:
            // arr = np.arange(12).reshape(3, 4)
            // sliced = arr[1:, ::2]  # rows 1-2, every other column
            // Result: [4, 6, 8, 10]

            var arr = np.arange(12).reshape(3, 4);
            var sliced = arr["1:, ::2"];
            var expected = new[] { 4, 6, 8, 10 };

            using var iter = NpyIterRef.New(sliced);
            var values = new List<int>();

            do
            {
                values.Add(iter.GetValue<int>(0));
            } while (iter.Iternext());

            CollectionAssert.AreEqual(expected, values.ToArray(),
                "Sliced array iteration must match NumPy exactly");
        }

        // =====================================================================
        // Test 5: Transposed array iteration
        // NumPy iterates in memory order, so transposed (F-contiguous) iterates [0,1,2,3,4,5]
        // =====================================================================
        [TestMethod]
        public void Battle_TransposedArrayIteration()
        {
            // NumPy:
            // arr = np.arange(6).reshape(2, 3)
            // trans = arr.T
            // with np.nditer(trans) as it:
            //     for x in it: values.append(int(x))
            // Result: [0, 1, 2, 3, 4, 5] (memory order, not logical order)

            var arr = np.arange(6).reshape(2, 3);
            var trans = arr.T;
            var expected = new[] { 0, 1, 2, 3, 4, 5 };

            using var iter = NpyIterRef.New(trans);
            var values = new List<int>();

            do
            {
                values.Add(iter.GetValue<int>(0));
            } while (iter.Iternext());

            CollectionAssert.AreEqual(expected, values.ToArray(),
                "Transposed array iteration must match NumPy memory order");
        }

        // =====================================================================
        // Test 6: Reversed array iteration
        // NumPy flips negative strides to iterate memory order: [0,1,2,3,4,5]
        // =====================================================================
        [TestMethod]
        public void Battle_ReversedArrayIteration()
        {
            // NumPy:
            // arr = np.arange(6).reshape(2, 3)
            // rev = arr[::-1, ::-1]
            // with np.nditer(rev) as it:
            //     for x in it: values.append(int(x))
            // Result: [0, 1, 2, 3, 4, 5] (memory order due to NEGPERM)

            var arr = np.arange(6).reshape(2, 3);
            var rev = arr["::-1, ::-1"];
            var expected = new[] { 0, 1, 2, 3, 4, 5 };

            using var iter = NpyIterRef.New(rev);
            var values = new List<int>();

            do
            {
                values.Add(iter.GetValue<int>(0));
            } while (iter.Iternext());

            CollectionAssert.AreEqual(expected, values.ToArray(),
                "Reversed array iteration must match NumPy memory order (NEGPERM)");
        }

        // =====================================================================
        // Test 7: Multi-index tracking
        // NumPy: [((0,0),0), ((0,1),1), ((0,2),2), ((1,0),3), ((1,1),4), ((1,2),5)]
        // =====================================================================
        [TestMethod]
        public void Battle_MultiIndexTracking()
        {
            // NumPy:
            // with np.nditer(arr, flags=['multi_index']) as it:
            //     while not it.finished:
            //         indices.append((it.multi_index, int(it[0])))
            //         it.iternext()

            var arr = np.arange(6).reshape(2, 3);
            var expected = new[]
            {
                ((0L, 0L), 0), ((0L, 1L), 1), ((0L, 2L), 2),
                ((1L, 0L), 3), ((1L, 1L), 4), ((1L, 2L), 5)
            };

            using var iter = NpyIterRef.New(arr, NpyIterGlobalFlags.MULTI_INDEX);
            var results = new List<((long, long), int)>();
            Span<long> mi = stackalloc long[2];

            do
            {
                iter.GetMultiIndex(mi);
                results.Add(((mi[0], mi[1]), iter.GetValue<int>(0)));
            } while (iter.Iternext());

            CollectionAssert.AreEqual(expected, results.ToArray(),
                "Multi-index tracking must match NumPy exactly");
        }

        // =====================================================================
        // Test 8: C_INDEX tracking
        // NumPy: [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
        // =====================================================================
        [TestMethod]
        public void Battle_CIndexTracking()
        {
            // NumPy:
            // with np.nditer(arr, flags=['c_index']) as it:
            //     while not it.finished:
            //         indices.append((it.index, int(it[0])))
            //         it.iternext()

            var arr = np.arange(6).reshape(2, 3);
            var expected = new[] { (0L, 0), (1L, 1), (2L, 2), (3L, 3), (4L, 4), (5L, 5) };

            using var iter = NpyIterRef.New(arr, NpyIterGlobalFlags.C_INDEX);
            var results = new List<(long, int)>();

            do
            {
                results.Add((iter.GetIndex(), iter.GetValue<int>(0)));
            } while (iter.Iternext());

            CollectionAssert.AreEqual(expected, results.ToArray(),
                "C_INDEX tracking must match NumPy exactly");
        }

        // =====================================================================
        // Test 9: Many operands (10)
        // NumPy: First values = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
        // =====================================================================
        [TestMethod]
        public void Battle_ManyOperands10()
        {
            // NumPy:
            // arrays = [np.array([i, i+1, i+2]) for i in range(0, 100, 10)]
            // First iteration: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

            var arrays = new NDArray[10];
            var opFlags = new NpyIterPerOpFlags[10];
            for (int i = 0; i < 10; i++)
            {
                arrays[i] = np.array(new long[] { i * 10, i * 10 + 1, i * 10 + 2 });
                opFlags[i] = NpyIterPerOpFlags.READONLY;
            }

            var expectedFirst = new long[] { 0, 10, 20, 30, 40, 50, 60, 70, 80, 90 };

            using var iter = NpyIterRef.MultiNew(10, arrays, NpyIterGlobalFlags.None,
                NPY_ORDER.NPY_KEEPORDER, NPY_CASTING.NPY_NO_CASTING, opFlags);

            // Get first iteration values
            var firstValues = new long[10];
            for (int op = 0; op < 10; op++)
            {
                firstValues[op] = iter.GetValue<long>(op);
            }

            CollectionAssert.AreEqual(expectedFirst, firstValues,
                "10 operand first values must match NumPy exactly");
        }

        // =====================================================================
        // Test 10: 3D array iteration
        // NumPy: First 10 = [0,1,2,3,4,5,6,7,8,9], Last 10 = [14..23], Count = 24
        // =====================================================================
        [TestMethod]
        public void Battle_3DArrayIteration()
        {
            // NumPy:
            // arr = np.arange(24).reshape(2, 3, 4)
            // First 10: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
            // Last 10: [14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
            // Total: 24

            var arr = np.arange(24).reshape(2, 3, 4);
            var expectedFirst10 = new[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
            var expectedLast10 = new[] { 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 };

            using var iter = NpyIterRef.New(arr);
            var values = new List<int>();

            do
            {
                values.Add(iter.GetValue<int>(0));
            } while (iter.Iternext());

            Assert.AreEqual(24, values.Count, "Total count must be 24");
            CollectionAssert.AreEqual(expectedFirst10, values.Take(10).ToArray(),
                "First 10 values must match NumPy");
            CollectionAssert.AreEqual(expectedLast10, values.Skip(14).ToArray(),
                "Last 10 values must match NumPy");
        }

        // =====================================================================
        // Test 11: Scalar iteration
        // NumPy: [42]
        // =====================================================================
        [TestMethod]
        public void Battle_ScalarIteration()
        {
            // NumPy:
            // scalar = np.array(42)
            // with np.nditer(scalar) as it:
            //     for x in it: values.append(int(x))
            // Result: [42]

            var scalar = np.array(42);
            var expected = new[] { 42 };

            using var iter = NpyIterRef.New(scalar);
            var values = new List<int>();

            do
            {
                values.Add(iter.GetValue<int>(0));
            } while (iter.Iternext());

            CollectionAssert.AreEqual(expected, values.ToArray(),
                "Scalar iteration must match NumPy");
        }

        // =====================================================================
        // Test 12: Empty array
        // NumPy: Iteration count = 0
        // =====================================================================
        [TestMethod]
        public void Battle_EmptyArrayIteration()
        {
            // NumPy:
            // empty = np.array([], dtype=np.int32)
            // with np.nditer(empty, flags=['zerosize_ok']) as it:
            //     for x in it: count += 1
            // Result: count = 0

            var empty = np.array(new int[0]);

            using var iter = NpyIterRef.New(empty, NpyIterGlobalFlags.ZEROSIZE_OK);

            int count = 0;
            // For empty arrays, Iternext returns false immediately or the loop doesn't execute
            if (iter.IterSize > 0)
            {
                do
                {
                    count++;
                } while (iter.Iternext());
            }

            Assert.AreEqual(0, count, "Empty array iteration count must be 0");
        }

        // =====================================================================
        // Test 13: Complex broadcasting (1,4) x (3,1) = (3,4)
        // NumPy pairs in row-major: (0,0),(1,0),(2,0),(3,0), (0,1),(1,1)...
        // =====================================================================
        [TestMethod]
        public void Battle_ComplexBroadcasting()
        {
            // NumPy:
            // a = np.arange(4).reshape(1, 4)  # [[0,1,2,3]]
            // b = np.arange(3).reshape(3, 1)  # [[0],[1],[2]]
            // pairs: [(0,0),(1,0),(2,0),(3,0), (0,1),(1,1),(2,1),(3,1), (0,2),(1,2),(2,2),(3,2)]

            var a = np.arange(4).reshape(1, 4);
            var b = np.arange(3).reshape(3, 1);

            // NumPy iterates in C-order over broadcast shape (3,4)
            var expected = new[]
            {
                (0, 0), (1, 0), (2, 0), (3, 0),
                (0, 1), (1, 1), (2, 1), (3, 1),
                (0, 2), (1, 2), (2, 2), (3, 2)
            };

            using var iter = NpyIterRef.MultiNew(
                2, new[] { a, b },
                NpyIterGlobalFlags.None,
                NPY_ORDER.NPY_KEEPORDER,
                NPY_CASTING.NPY_NO_CASTING,
                new[] { NpyIterPerOpFlags.READONLY, NpyIterPerOpFlags.READONLY });

            var pairs = new List<(int, int)>();

            do
            {
                pairs.Add((iter.GetValue<int>(0), iter.GetValue<int>(1)));
            } while (iter.Iternext());

            CollectionAssert.AreEqual(expected, pairs.ToArray(),
                "Complex broadcasting must match NumPy exactly");
        }

        // =====================================================================
        // Test 14: Negative stride array (reversed 1D)
        // NumPy flips to memory order: [0,1,2,3,4,5]
        // =====================================================================
        [TestMethod]
        public void Battle_NegativeStrideArray()
        {
            // NumPy:
            // arr = np.arange(6)[::-1]  # [5,4,3,2,1,0] with negative stride
            // Iteration (NEGPERM flips): [0, 1, 2, 3, 4, 5]

            var arr = np.arange(6)["::-1"];
            var expected = new[] { 0, 1, 2, 3, 4, 5 };

            using var iter = NpyIterRef.New(arr);
            var values = new List<int>();

            do
            {
                values.Add(iter.GetValue<int>(0));
            } while (iter.Iternext());

            CollectionAssert.AreEqual(expected, values.ToArray(),
                "Negative stride array must iterate in memory order (NEGPERM)");
        }

        // =====================================================================
        // Test 15: 50 operands (beyond NumPy 1.x limit of 32)
        // NumPy 2.x: First values = [0, 1, 2, ..., 49]
        // =====================================================================
        [TestMethod]
        public void Battle_50Operands()
        {
            // NumPy:
            // arrays50 = [np.array([i]) for i in range(50)]
            // First values: [0, 1, 2, ..., 49]

            var arrays = new NDArray[50];
            var opFlags = new NpyIterPerOpFlags[50];
            var expectedFirst = new int[50];

            for (int i = 0; i < 50; i++)
            {
                arrays[i] = np.array(new int[] { i });
                opFlags[i] = NpyIterPerOpFlags.READONLY;
                expectedFirst[i] = i;
            }

            using var iter = NpyIterRef.MultiNew(50, arrays, NpyIterGlobalFlags.None,
                NPY_ORDER.NPY_KEEPORDER, NPY_CASTING.NPY_NO_CASTING, opFlags);

            var firstValues = new int[50];
            for (int op = 0; op < 50; op++)
            {
                firstValues[op] = iter.GetValue<int>(op);
            }

            CollectionAssert.AreEqual(expectedFirst, firstValues,
                "50 operand first values must match NumPy exactly");
        }

        // =====================================================================
        // Test 16: 100 operands (NumSharp unlimited, beyond NumPy's NPY_MAXARGS=64)
        // =====================================================================
        [TestMethod]
        public void Battle_100Operands_BeyondNumPyLimit()
        {
            // NumSharp supports unlimited operands
            // This tests beyond NumPy's NPY_MAXARGS=64 limit

            var arrays = new NDArray[100];
            var opFlags = new NpyIterPerOpFlags[100];
            var expectedFirst = new int[100];

            for (int i = 0; i < 100; i++)
            {
                arrays[i] = np.array(new int[] { i * 10, i * 10 + 1 });
                opFlags[i] = NpyIterPerOpFlags.READONLY;
                expectedFirst[i] = i * 10;  // First element
            }

            using var iter = NpyIterRef.MultiNew(100, arrays, NpyIterGlobalFlags.None,
                NPY_ORDER.NPY_KEEPORDER, NPY_CASTING.NPY_NO_CASTING, opFlags);

            Assert.AreEqual(100, iter.NOp, "Should have 100 operands");
            Assert.AreEqual(2, iter.IterSize, "Should iterate 2 times (array length)");

            // Verify first iteration values
            var firstValues = new int[100];
            for (int op = 0; op < 100; op++)
            {
                firstValues[op] = iter.GetValue<int>(op);
            }
            CollectionAssert.AreEqual(expectedFirst, firstValues,
                "100 operand first values must be correct");

            // Move to second iteration and verify
            Assert.IsTrue(iter.Iternext(), "Should have second iteration");
            var secondValues = new int[100];
            var expectedSecond = new int[100];
            for (int op = 0; op < 100; op++)
            {
                secondValues[op] = iter.GetValue<int>(op);
                expectedSecond[op] = op * 10 + 1;  // Second element
            }
            CollectionAssert.AreEqual(expectedSecond, secondValues,
                "100 operand second values must be correct");

            // Should be finished
            Assert.IsFalse(iter.Iternext(), "Should be finished after 2 iterations");
        }

        // =====================================================================
        // Test 17: Verify iteration order with non-contiguous view
        // =====================================================================
        [TestMethod]
        public void Battle_NonContiguousViewOrder()
        {
            // Create a non-contiguous view via slicing
            var arr = np.arange(20).reshape(4, 5);
            var view = arr["::2, 1::2"];  // Every other row, columns 1,3

            // Expected shape is (2, 2) with values [[1,3], [11,13]]
            // C-order iteration: [1, 3, 11, 13]
            var expected = new[] { 1, 3, 11, 13 };

            using var iter = NpyIterRef.New(view);
            var values = new List<int>();

            do
            {
                values.Add(iter.GetValue<int>(0));
            } while (iter.Iternext());

            CollectionAssert.AreEqual(expected, values.ToArray(),
                "Non-contiguous view must iterate in correct order");
        }

        // =====================================================================
        // Test 18: Verify multi-index with transposed array
        // =====================================================================
        [TestMethod]
        public void Battle_MultiIndexWithTransposed()
        {
            var arr = np.arange(6).reshape(2, 3);
            var trans = arr.T;  // Shape (3, 2)

            // Multi-index should follow the logical shape (3, 2)
            // But iteration follows memory order

            using var iter = NpyIterRef.New(trans, NpyIterGlobalFlags.MULTI_INDEX);

            var results = new List<(long row, long col, int val)>();
            Span<long> mi = stackalloc long[2];
            do
            {
                iter.GetMultiIndex(mi);
                results.Add((mi[0], mi[1], iter.GetValue<int>(0)));
            } while (iter.Iternext());

            // Verify we get all 6 elements with valid multi-indices
            Assert.AreEqual(6, results.Count);

            // Values should be 0-5 (memory order)
            var values = results.Select(r => r.val).ToArray();
            CollectionAssert.AreEqual(new[] { 0, 1, 2, 3, 4, 5 }, values);
        }

        // =====================================================================
        // Test 19: Verify GotoMultiIndex works correctly
        // =====================================================================
        [TestMethod]
        public void Battle_GotoMultiIndex()
        {
            var arr = np.arange(12).reshape(3, 4);

            using var iter = NpyIterRef.New(arr, NpyIterGlobalFlags.MULTI_INDEX);

            // Jump to position (1, 2) which should have value 6
            iter.GotoMultiIndex(new long[] { 1, 2 });
            Assert.AreEqual(6, iter.GetValue<int>(0));

            // Jump to position (2, 3) which should have value 11
            iter.GotoMultiIndex(new long[] { 2, 3 });
            Assert.AreEqual(11, iter.GetValue<int>(0));

            // Jump back to start
            iter.GotoMultiIndex(new long[] { 0, 0 });
            Assert.AreEqual(0, iter.GetValue<int>(0));
        }

        // =====================================================================
        // Test 20: Verify external loop flag
        // =====================================================================
        [TestMethod]
        public void Battle_ExternalLoop()
        {
            // NumPy with external_loop returns contiguous chunks
            var arr = np.arange(12).reshape(3, 4);

            using var iter = NpyIterRef.New(arr, NpyIterGlobalFlags.EXTERNAL_LOOP);

            // With external loop on contiguous array, should get one large chunk
            Assert.IsTrue(iter.HasExternalLoop);

            // Inner loop size should be the full array for contiguous
            long* innerSizePtr = iter.GetInnerLoopSizePtr();
            // For contiguous C-order array, inner loop should cover all elements
            Assert.IsTrue(*innerSizePtr >= 1, "Inner loop size should be at least 1");
        }

        // =====================================================================
        // Test 21: Verify buffered iteration with type casting
        // =====================================================================
        [TestMethod]
        public void Battle_BufferedWithCasting()
        {
            // Create int32 array, iterate as float64
            var arr = np.array(new int[] { 1, 2, 3 });

            using var iter = NpyIterRef.AdvancedNew(
                1, new[] { arr },
                NpyIterGlobalFlags.BUFFERED,
                NPY_ORDER.NPY_KEEPORDER,
                NPY_CASTING.NPY_SAFE_CASTING,
                new[] { NpyIterPerOpFlags.READONLY },
                new[] { NPTypeCode.Double });

            var values = new List<double>();
            do
            {
                values.Add(iter.GetValue<double>(0));
            } while (iter.Iternext());

            CollectionAssert.AreEqual(new[] { 1.0, 2.0, 3.0 }, values.ToArray(),
                "Buffered casting must convert int32 to float64 correctly");
        }

        // =====================================================================
        // Test 22: Full iteration then reset
        // =====================================================================
        [TestMethod]
        public void Battle_FullIterationThenReset()
        {
            var arr = np.arange(6).reshape(2, 3);

            using var iter = NpyIterRef.New(arr);

            // First full iteration
            var values1 = new List<int>();
            do
            {
                values1.Add(iter.GetValue<int>(0));
            } while (iter.Iternext());

            // Reset
            iter.Reset();

            // Second full iteration should produce same results
            var values2 = new List<int>();
            do
            {
                values2.Add(iter.GetValue<int>(0));
            } while (iter.Iternext());

            CollectionAssert.AreEqual(values1, values2,
                "Reset must allow identical re-iteration");
        }

        // =====================================================================
        // Test 23: Copy iterator preserves state
        // =====================================================================
        [TestMethod]
        public void Battle_CopyIteratorPreservesState()
        {
            var arr = np.arange(10);

            using var iter = NpyIterRef.New(arr);

            // Advance to position 5
            for (int i = 0; i < 5; i++)
                iter.Iternext();

            Assert.AreEqual(5, iter.GetValue<int>(0));

            // Copy
            using var copy = iter.Copy();

            // Copy should be at same position
            Assert.AreEqual(5, copy.GetValue<int>(0));

            // Advancing copy shouldn't affect original
            copy.Iternext();
            Assert.AreEqual(6, copy.GetValue<int>(0));
            Assert.AreEqual(5, iter.GetValue<int>(0));
        }

        // =====================================================================
        // Test 24: Ranged iteration
        // =====================================================================
        [TestMethod]
        public void Battle_RangedIteration()
        {
            var arr = np.arange(10);

            using var iter = NpyIterRef.New(arr);

            // Set range to iterate only elements 3-7
            iter.ResetToIterIndexRange(3, 7);

            var values = new List<int>();
            do
            {
                values.Add(iter.GetValue<int>(0));
            } while (iter.Iternext());

            CollectionAssert.AreEqual(new[] { 3, 4, 5, 6 }, values.ToArray(),
                "Ranged iteration must only iterate specified range");
        }
    }
}
