using NumSharp;
using NumSharp.Backends;
using NumSharp.Backends.Iteration;

namespace NeuralNetwork.NumSharp.MnistMlp
{
    /// <summary>
    /// 2-layer MLP forward pass that folds the (bias-add + ReLU) post-matmul
    /// work into a single NpyIter kernel per layer.
    ///
    /// Structure per layer:
    ///   preact = np.dot(x, W)              // unavoidable matmul (different loop shape)
    ///   y      = NpyIter over (preact, b, y) compiling   Max(in0 + in1, 0)
    ///
    /// Two matmuls plus two NpyIter invocations total. The activation (ReLU)
    /// and bias addition happen in ONE element-wise pass, sharing a single
    /// 4x-unrolled SIMD loop generated by ILKernelGenerator.CompileInnerLoop.
    /// No intermediate NDArray is allocated for `preact + b` — the fused
    /// kernel reads both inputs stride-by-stride and writes the ReLU'd sum
    /// straight into the output buffer.
    ///
    /// The bias (shape (N,)) broadcasts naturally across the batch dim of
    /// preact (shape (batch, N)) because NpyIter aligns shapes from the
    /// right and inserts stride-0 dims where needed.
    /// </summary>
    public static class FusedMlp
    {
        // Cache keys keep IL compilation at O(1) per process: the kernels are
        // emitted on first use and reused across every forward pass thereafter.
        private const string BiasReluKey = "mnist_mlp_fused_bias_relu_f32";
        private const string BiasOnlyKey = "mnist_mlp_fused_bias_only_f32";

        /// <summary>
        /// Runs the forward pass. Expects float32 inputs/weights/biases for the
        /// SIMD fast path; returns a fresh (batch, OutputDim) float32 array.
        /// </summary>
        public static NDArray Forward(NDArray x, NDArray W1, NDArray b1, NDArray W2, NDArray b2)
        {
            // Layer 1: hidden = ReLU(x @ W1 + b1)
            NDArray preact1 = np.dot(x, W1);
            NDArray hidden  = np.empty_like(preact1);
            FuseBiasPlusRelu(preact1, b1, hidden);

            // Layer 2: logits = hidden @ W2 + b2 (no ReLU — we want raw logits)
            NDArray preact2 = np.dot(hidden, W2);
            NDArray logits  = np.empty_like(preact2);
            FuseBiasOnly(preact2, b2, logits);

            return logits;
        }

        /// <summary>
        /// output[i,j] = max(preact[i,j] + bias[j], 0), all float32, in a single
        /// NpyIter element-wise sweep. This is the whole point of the
        /// experiment: one iterator, one kernel, zero intermediate arrays.
        /// </summary>
        private static void FuseBiasPlusRelu(NDArray preact, NDArray bias, NDArray output)
        {
            using var iter = NpyIterRef.MultiNew(
                nop: 3,
                op: new[] { preact, bias, output },
                flags: NpyIterGlobalFlags.EXTERNAL_LOOP,
                order: NPY_ORDER.NPY_KEEPORDER,
                casting: NPY_CASTING.NPY_NO_CASTING,
                opFlags: new[]
                {
                    NpyIterPerOpFlags.READONLY,
                    NpyIterPerOpFlags.READONLY,
                    NpyIterPerOpFlags.WRITEONLY,
                });

            // Max(Input(0) + Input(1), 0) — addition and the ReLU clamp in one expression.
            var expr = NpyExpr.Max(
                NpyExpr.Input(0) + NpyExpr.Input(1),
                NpyExpr.Const(0f));

            iter.ExecuteExpression(
                expr,
                inputTypes: new[] { NPTypeCode.Single, NPTypeCode.Single },
                outputType: NPTypeCode.Single,
                cacheKey: BiasReluKey);
        }

        /// <summary>
        /// output[i,j] = preact[i,j] + bias[j]. The final layer emits raw
        /// logits, so only the bias add is fused — no activation.
        /// </summary>
        private static void FuseBiasOnly(NDArray preact, NDArray bias, NDArray output)
        {
            using var iter = NpyIterRef.MultiNew(
                nop: 3,
                op: new[] { preact, bias, output },
                flags: NpyIterGlobalFlags.EXTERNAL_LOOP,
                order: NPY_ORDER.NPY_KEEPORDER,
                casting: NPY_CASTING.NPY_NO_CASTING,
                opFlags: new[]
                {
                    NpyIterPerOpFlags.READONLY,
                    NpyIterPerOpFlags.READONLY,
                    NpyIterPerOpFlags.WRITEONLY,
                });

            var expr = NpyExpr.Input(0) + NpyExpr.Input(1);

            iter.ExecuteExpression(
                expr,
                inputTypes: new[] { NPTypeCode.Single, NPTypeCode.Single },
                outputType: NPTypeCode.Single,
                cacheKey: BiasOnlyKey);
        }
    }
}
