using System;
using NumSharp.Backends.Kernels;

namespace NumSharp.Backends
{
    public partial class DefaultEngine
    {
        // =============================================================================
        // ClipNDArray — np.clip dispatcher
        // =============================================================================
        //
        // This class only handles policy: dtype promotion (NEP-50 weak scalar),
        // @out validation, deciding whether bounds are scalar vs array, and
        // contiguity gating. The actual element-wise loop is generated by
        // DirectILKernelGenerator.Clip as a DynamicMethod and cached per
        // (dtype, mode, kind). No SIMD width is hardcoded — the kernel adapts
        // to V128 / V256 / V512 via GetVectorContainerType().
        //
        // Two execution paths, no materializing copy for non-contiguous input:
        //   * Contiguous fast path — every operand C-contiguous offset-0 → the IL
        //     kernel (SIMD where the dtype supports it) in one src→dst pass.
        //   * Strided path (ClipStrided) — strided / transposed / sliced / F-order /
        //     broadcast (stride=0) operands are read through their own strides in
        //     C-order via FlatStrideOffset, writing a fresh C-contiguous result. Its
        //     per-element clamp mirrors the IL kernel's NaN-propagating semantics
        //     exactly (incl. the signed-zero tie), so both paths agree bit-for-bit.
        //   A dtype change still goes through Cast (a genuine conversion), and a
        //   non-C-contiguous @out is relayed with copyto (writing a strided output
        //   is inherent, not a kernel-dodge copy).
        // =============================================================================

        public override NDArray ClipNDArray(NDArray lhs, NDArray min, NDArray max, Type dtype, NDArray @out = null)
            => ClipNDArray(lhs, min, max, dtype?.GetTypeCode(), @out);

        public override unsafe NDArray ClipNDArray(NDArray lhs, NDArray min, NDArray max, NPTypeCode? typeCode = null, NDArray @out = null)
        {
            // ---- Output dtype (explicit `dtype=` wins; otherwise NEP-50 weak-scalar promote)
            NPTypeCode outType;
            if (typeCode.HasValue)
                outType = typeCode.Value;
            else
            {
                outType = lhs.typecode;
                outType = PromoteClipBound(outType, min);
                outType = PromoteClipBound(outType, max);
            }

            // ---- @out validation (shape, writeable, dtype)
            if (@out is not null)
            {
                NumSharpException.ThrowIfNotWriteable(@out.Shape);
                if (@out.Shape != lhs.Shape)
                    throw new ArgumentException($"@out's shape ({@out.Shape}) must match lhs's shape ({lhs.Shape}).'");
                if (@out.GetTypeCode != outType)
                    throw new ArgumentException(
                        $"Cannot cast ufunc 'clip' output from dtype('{outType.AsNumpyDtypeName()}') to dtype('{@out.GetTypeCode.AsNumpyDtypeName()}') with casting rule 'same_kind'.");
            }

            // ---- Empty input — bypass the kernel entirely
            if (lhs.size == 0)
                return @out ?? Cast(lhs, outType, copy: true);

            // ---- Both bounds null — clip is a typed copy
            if (min is null && max is null)
            {
                if (@out is null) return Cast(lhs, outType, copy: true);
                np.copyto(@out, Cast(lhs, outType, copy: false));
                return @out;
            }

            // ---- Special-case NaN scalar bounds on float dtypes (NumPy: entire
            //      result is NaN). The IL kernel uses Vector.Min/Max which on x86
            //      do not propagate NaN-in-bounds in the second-operand position
            //      consistently across vendors, so we short-circuit here.
            if ((outType == NPTypeCode.Single || outType == NPTypeCode.Double)
                && ScalarIsNaN(min) || ScalarIsNaN(max))
            {
                var nan = outType == NPTypeCode.Double
                    ? np.full(lhs.Shape, double.NaN)
                    : np.full(lhs.Shape, float.NaN);
                if (@out is null) return nan;
                np.copyto(@out, nan);
                return @out;
            }

            // ---- Decide bound kinds and route through DirectILKernelGenerator
            bool minScalar = min is null || min.ndim == 0;
            bool maxScalar = max is null || max.ndim == 0;
            bool allScalarBounds = minScalar && maxScalar;

            // Build dispatch tuple for the IL kernel
            DirectILKernelGenerator.ClipMode mode =
                min is null ? DirectILKernelGenerator.ClipMode.MaxOnly :
                max is null ? DirectILKernelGenerator.ClipMode.MinOnly :
                              DirectILKernelGenerator.ClipMode.BothBounds;
            DirectILKernelGenerator.ClipBoundsKind kind =
                allScalarBounds ? DirectILKernelGenerator.ClipBoundsKind.Scalar
                                : DirectILKernelGenerator.ClipBoundsKind.Array;

            // Cast bounds to outType. For scalar (0-d) bounds astype is O(1);
            // for array bounds it's broadcast_to(target_shape) + astype, with
            // the same-shape/same-dtype short-circuit handled by PrepareBound.
            NDArray loCast = null, hiCast = null;
            if (kind == DirectILKernelGenerator.ClipBoundsKind.Scalar)
            {
                // ScalarBoundReady avoids the astype CLONE when the bound is already a
                // contiguous offset-0 scalar of outType (the dominant np.clip(arr, lo, hi)
                // case where lo/hi arrive as same-dtype scalars) — RunClipKernel reads the
                // value through .Address, which is only correct at offset 0. Measured ~0.9µs
                // saved per scalar bound at small N (the astype path's dominant cost there).
                if (min is not null) loCast = ScalarBoundReady(min, outType) ? min : min.astype(outType);
                if (max is not null) hiCast = ScalarBoundReady(max, outType) ? max : max.astype(outType);
            }
            else
            {
                loCast = PrepareBound(min, lhs.Shape, outType);
                hiCast = PrepareBound(max, lhs.Shape, outType);
            }

            // ---- Pick src and route to the contiguous IL kernel or the strided loop
            bool arrayBounds = kind == DirectILKernelGenerator.ClipBoundsKind.Array;

            // src at outType. Cast performs only a genuine dtype change; the source LAYOUT is
            // preserved (no contiguity copy). Strided / F-order / sliced views are read through
            // their strides by the strided path below — the previous code materialized a C-order
            // copy here (and a second copy('C') for array bounds), the rejected anti-pattern.
            NDArray srcArr = lhs.GetTypeCode == outType ? lhs : Cast(lhs, outType, copy: true);

            bool srcFlat = srcArr.Shape.IsContiguous && srcArr.Shape.Offset == 0;
            // The flat IL kernel walks src/dst/lo/hi linearly and pairs them by C-order index,
            // so array bounds must also be C-contiguous offset-0; scalar bounds are one value
            // broadcast to every lane and are always fine.
            bool boundsFlat = !arrayBounds
                || ((loCast is null || (loCast.Shape.IsContiguous && loCast.Shape.Offset == 0))
                    && (hiCast is null || (hiCast.Shape.IsContiguous && hiCast.Shape.Offset == 0)));

            // Fresh C-contiguous shape for any allocated result — must NOT inherit lhs's strides
            // (np.empty(lhs.Shape) would clone a strided/F-order layout, which the linear dst
            // writes below would then mis-address).
            Shape cShape = new Shape((long[])lhs.shape.Clone());

            if (srcFlat && boundsFlat)
            {
                // Fast path: every operand plainly C-contiguous — IL kernel (SIMD where the
                // dtype supports it) in a single src→dst pass (or straight into a C-order @out).
                if (@out is not null && (!@out.Shape.IsContiguous || @out.Shape.Offset != 0))
                {
                    var tmp = np.empty(cShape, outType);
                    RunClipKernel(srcArr, tmp, loCast, hiCast, outType, mode, kind);
                    np.copyto(@out, tmp);    // relay C-order result into the strided @out
                    return @out;
                }
                var dstFast = @out ?? np.empty(cShape, outType);
                RunClipKernel(srcArr, dstFast, loCast, hiCast, outType, mode, kind);
                return dstFast;
            }

            // ---- Strided / F-order src or array bounds: read every operand through its own
            //      strides in C-order, writing a fresh C-contiguous result — no copy. copyto
            //      relays into a non-C-contiguous @out (writing a strided output is inherent).
            NDArray outBuf = (@out is not null && @out.Shape.IsContiguous && @out.Shape.Offset == 0)
                ? @out
                : np.empty(cShape, outType);
            ClipStrided(srcArr, outBuf, loCast, hiCast, outType, mode, kind);
            if (@out is not null && !ReferenceEquals(outBuf, @out))
            {
                np.copyto(@out, outBuf);
                return @out;
            }
            return outBuf;
        }

        // Extract pointers and invoke the flat IL clip kernel. src/dst (and array bounds) must
        // be C-contiguous offset-0; scalar bounds are single values.
        private static unsafe void RunClipKernel(NDArray src, NDArray dst, NDArray loCast, NDArray hiCast,
            NPTypeCode outType, DirectILKernelGenerator.ClipMode mode, DirectILKernelGenerator.ClipBoundsKind kind)
        {
            void* srcPtr = (void*)src.Address;
            void* dstPtr = (void*)dst.Address;
            void* loPtr  = loCast is null ? null : (void*)loCast.Address;
            void* hiPtr  = hiCast is null ? null : (void*)hiCast.Address;
            DirectILKernelGenerator.Clip(outType, mode, kind, srcPtr, dstPtr, dst.size, loPtr, hiPtr);
        }

        // Strided clip: read src and (array) bounds through their own strides in C-order, writing
        // a C-contiguous dst. Per-element semantics mirror the IL kernel's scalar tail exactly —
        // Math.Max/Min for sized numerics + decimal, NaN-aware helpers for Half / Complex, numeric
        // ordering for Char (read as UInt16) — so results are identical to the contiguous path.
        private static unsafe void ClipStrided(NDArray src, NDArray dst, NDArray loCast, NDArray hiCast,
            NPTypeCode outType, DirectILKernelGenerator.ClipMode mode, DirectILKernelGenerator.ClipBoundsKind kind)
        {
            long n = dst.size;
            var dims = dst.shape;
            int ndim = dst.ndim;
            bool needLo = mode != DirectILKernelGenerator.ClipMode.MaxOnly;
            bool needHi = mode != DirectILKernelGenerator.ClipMode.MinOnly;
            bool arr = kind == DirectILKernelGenerator.ClipBoundsKind.Array;

            byte* sBase = (byte*)src.Address + src.Shape.offset * src.dtypesize;
            bool srcC = src.Shape.IsContiguous && src.Shape.offset == 0;
            var srcStr = src.strides;

            byte* loBase = loCast is null ? null : (byte*)loCast.Address + loCast.Shape.offset * loCast.dtypesize;
            byte* hiBase = hiCast is null ? null : (byte*)hiCast.Address + hiCast.Shape.offset * hiCast.dtypesize;
            long[] loStr = loCast?.strides;
            long[] hiStr = hiCast?.strides;
            bool loC = !arr || loCast is null || (loCast.Shape.IsContiguous && loCast.Shape.offset == 0);
            bool hiC = !arr || hiCast is null || (hiCast.Shape.IsContiguous && hiCast.Shape.offset == 0);

            switch (outType)
            {
                case NPTypeCode.Byte:    ClipStridedT<byte>(sBase, (byte*)dst.Address, loBase, hiBase, dims, srcStr, loStr, hiStr, ndim, srcC, arr, loC, hiC, n, needLo, needHi, &Math.Max, &Math.Min); break;
                case NPTypeCode.SByte:   ClipStridedT<sbyte>(sBase, (sbyte*)dst.Address, loBase, hiBase, dims, srcStr, loStr, hiStr, ndim, srcC, arr, loC, hiC, n, needLo, needHi, &Math.Max, &Math.Min); break;
                case NPTypeCode.Int16:   ClipStridedT<short>(sBase, (short*)dst.Address, loBase, hiBase, dims, srcStr, loStr, hiStr, ndim, srcC, arr, loC, hiC, n, needLo, needHi, &Math.Max, &Math.Min); break;
                case NPTypeCode.UInt16:  ClipStridedT<ushort>(sBase, (ushort*)dst.Address, loBase, hiBase, dims, srcStr, loStr, hiStr, ndim, srcC, arr, loC, hiC, n, needLo, needHi, &Math.Max, &Math.Min); break;
                case NPTypeCode.Char:    ClipStridedT<ushort>(sBase, (ushort*)dst.Address, loBase, hiBase, dims, srcStr, loStr, hiStr, ndim, srcC, arr, loC, hiC, n, needLo, needHi, &Math.Max, &Math.Min); break;
                case NPTypeCode.Int32:   ClipStridedT<int>(sBase, (int*)dst.Address, loBase, hiBase, dims, srcStr, loStr, hiStr, ndim, srcC, arr, loC, hiC, n, needLo, needHi, &Math.Max, &Math.Min); break;
                case NPTypeCode.UInt32:  ClipStridedT<uint>(sBase, (uint*)dst.Address, loBase, hiBase, dims, srcStr, loStr, hiStr, ndim, srcC, arr, loC, hiC, n, needLo, needHi, &Math.Max, &Math.Min); break;
                case NPTypeCode.Int64:   ClipStridedT<long>(sBase, (long*)dst.Address, loBase, hiBase, dims, srcStr, loStr, hiStr, ndim, srcC, arr, loC, hiC, n, needLo, needHi, &Math.Max, &Math.Min); break;
                case NPTypeCode.UInt64:  ClipStridedT<ulong>(sBase, (ulong*)dst.Address, loBase, hiBase, dims, srcStr, loStr, hiStr, ndim, srcC, arr, loC, hiC, n, needLo, needHi, &Math.Max, &Math.Min); break;
                case NPTypeCode.Single:  ClipStridedT<float>(sBase, (float*)dst.Address, loBase, hiBase, dims, srcStr, loStr, hiStr, ndim, srcC, arr, loC, hiC, n, needLo, needHi, &DirectILKernelGenerator.FloatMaxNaN, &DirectILKernelGenerator.FloatMinNaN); break;
                case NPTypeCode.Double:  ClipStridedT<double>(sBase, (double*)dst.Address, loBase, hiBase, dims, srcStr, loStr, hiStr, ndim, srcC, arr, loC, hiC, n, needLo, needHi, &DirectILKernelGenerator.DoubleMaxNaN, &DirectILKernelGenerator.DoubleMinNaN); break;
                case NPTypeCode.Decimal: ClipStridedT<decimal>(sBase, (decimal*)dst.Address, loBase, hiBase, dims, srcStr, loStr, hiStr, ndim, srcC, arr, loC, hiC, n, needLo, needHi, &Math.Max, &Math.Min); break;
                case NPTypeCode.Half:    ClipStridedT<Half>(sBase, (Half*)dst.Address, loBase, hiBase, dims, srcStr, loStr, hiStr, ndim, srcC, arr, loC, hiC, n, needLo, needHi, &DirectILKernelGenerator.HalfMaxNaN, &DirectILKernelGenerator.HalfMinNaN); break;
                case NPTypeCode.Complex: ClipStridedT<System.Numerics.Complex>(sBase, (System.Numerics.Complex*)dst.Address, loBase, hiBase, dims, srcStr, loStr, hiStr, ndim, srcC, arr, loC, hiC, n, needLo, needHi, &DirectILKernelGenerator.ComplexMaxNaN, &DirectILKernelGenerator.ComplexMinNaN); break;
                default: throw new NotSupportedException($"clip not supported for {outType}");
            }
        }

        // One strided clip loop, shared across dtypes via Max/Min function pointers (no per-element
        // boxing or virtual dispatch). dst is C-contiguous; src and array bounds are read at
        // FlatStrideOffset(i) so any stride layout — incl. broadcast stride=0 — is honoured.
        private static unsafe void ClipStridedT<T>(
            byte* sBase, T* dst, byte* loBase, byte* hiBase,
            long[] dims, long[] srcStr, long[] loStr, long[] hiStr, int ndim,
            bool srcC, bool arr, bool loC, bool hiC,
            long n, bool needLo, bool needHi,
            delegate*<T, T, T> max, delegate*<T, T, T> min) where T : unmanaged
        {
            var s = (T*)sBase;
            var loA = (T*)loBase;
            var hiA = (T*)hiBase;
            T loScalar = (needLo && !arr && loBase != null) ? *loA : default;
            T hiScalar = (needHi && !arr && hiBase != null) ? *hiA : default;

            for (long i = 0; i < n; i++)
            {
                T v = s[srcC ? i : FlatStrideOffset(i, dims, srcStr, ndim)];
                if (needLo && loBase != null)
                {
                    T lo = arr ? loA[loC ? i : FlatStrideOffset(i, dims, loStr, ndim)] : loScalar;
                    v = max(v, lo);
                }
                if (needHi && hiBase != null)
                {
                    T hi = arr ? hiA[hiC ? i : FlatStrideOffset(i, dims, hiStr, ndim)] : hiScalar;
                    v = min(v, hi);
                }
                dst[i] = v;
            }
        }

        // ---- Policy helpers ---------------------------------------------------

        // NEP-50 weak-scalar promotion: a 0-d bound of the same kind
        // (int / float / complex / decimal) as outType is "weak" and doesn't
        // promote, mirroring how NumPy treats Python int/float literals.
        // Array bounds and cross-kind scalars promote via np.result_type.
        private static NPTypeCode PromoteClipBound(NPTypeCode outType, NDArray bound)
        {
            if (bound is null) return outType;
            if (bound.ndim == 0 && IsSameKind(outType, bound.typecode))
                return outType;
            return np.result_type(outType, bound.typecode);
        }

        private static bool IsSameKind(NPTypeCode a, NPTypeCode b)
        {
            int ga = a.GetGroup();
            int gb = b.GetGroup();
            // 0=Byte/Char, 1=signed int, 2=unsigned int  →  all "integer kind".
            bool aInt = ga >= 0 && ga <= 2;
            bool bInt = gb >= 0 && gb <= 2;
            if (aInt && bInt) return true;
            return ga == gb;
        }

        // Returns `bound` ready for the array-bounds kernel: matches lhs shape,
        // dtype outType, contiguous, offset zero. Returns the original instance
        // when those already hold (skips the otherwise-mandatory clone done by
        // `astype` on a same-dtype input).
        private static NDArray PrepareBound(NDArray bound, Shape targetShape, NPTypeCode outType)
        {
            if (bound is null) return null;
            if (bound.GetTypeCode == outType
                && bound.Shape.Equals(targetShape)
                && bound.Shape.IsContiguous
                && bound.Shape.Offset == 0)
            {
                return bound;
            }
            // Broadcast to the target shape and convert dtype. The result may stay
            // non-C-contiguous (broadcast stride=0 / F-order / strided) — that's fine:
            // ClipStrided reads the bound through its own strides at FlatStrideOffset(i),
            // pairing it correctly with the C-order result without a normalizing copy.
            return np.broadcast_to(bound, targetShape).astype(outType);
        }

        // True when a scalar (0-d) bound is already a value of outType at buffer offset 0,
        // so RunClipKernel can read it straight through .Address with no astype clone. A 0-d
        // VIEW with a non-zero offset (e.g. arr[i] used as a bound) still needs astype to
        // materialize the value at offset 0 — .Address ignores the offset.
        private static bool ScalarBoundReady(NDArray bound, NPTypeCode outType)
            => bound.GetTypeCode == outType && bound.Shape.offset == 0;

        // Returns true when `bound` is a 0-d scalar NDArray whose value is NaN.
        // Used to short-circuit float NaN-in-bounds → all-NaN result (NumPy).
        private static bool ScalarIsNaN(NDArray bound)
        {
            if (bound is null || bound.ndim != 0) return false;
            switch (bound.GetTypeCode)
            {
                case NPTypeCode.Double: return double.IsNaN(bound.GetDouble(0));
                case NPTypeCode.Single: return float.IsNaN(bound.GetSingle(0));
                case NPTypeCode.Half:   return Half.IsNaN(bound.GetHalf(0));
                default: return false;
            }
        }
    }
}
