/*
This file was generated by template ../NDArray.Elementwise.tt
In case you want to do some changes do the following 

1 ) adapt the tt file
2 ) execute powershell file "GenerateCode.ps1" on root level

*/
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Numerics;
using NumSharp.Shared;

namespace NumSharp.Backends
{
    public abstract partial class DefaultEngine
    {
        public virtual NDArray Sum(NDArray x, int axis = -1)
        {
            if (axis == -1)
            {
                switch (Type.GetTypeCode(x.dtype))
                {
                    case TypeCode.Int32:
                        return x.Data<int>().Sum();
                }
            }
            else if (axis == 0)
            {
                switch (Type.GetTypeCode(x.dtype))
                {
                    case TypeCode.Int32:
                        return x.Data<int>().Sum();
                }
            }

            throw new NotImplementedException($"DefaultEngine sum {x.dtype.Name} axis: {axis}");
        }
        
    }

}

