/*
Originally generated by the T4 template ../NDArray.Elementwise.tt (since removed).
This file is now hand-maintained — the template and GenerateCode.ps1 no longer exist.
*/

using System;

namespace NumSharp.Backends
{
    public partial class DefaultEngine
    {
        public override NDArray Sum(NDArray nd, int axis, Type dtype, bool keepdims = false)
        {
            return Sum(nd, axis, dtype != null ? dtype.GetTypeCode() : default(NPTypeCode?), keepdims);
        }

        public override NDArray Sum(NDArray nd, int? axis = null, NPTypeCode? typeCode = null, bool keepdims = false)
        {
            return ReduceAdd(nd, axis, keepdims, typeCode);
        }
    }
}
