using System;
using NumSharp.Backends.Kernels;

namespace NumSharp.Backends
{
    public partial class DefaultEngine
    {
        // =============================================================================
        // ClipNDArray — np.clip dispatcher
        // =============================================================================
        //
        // This class only handles policy: dtype promotion (NEP-50 weak scalar),
        // @out validation, deciding whether bounds are scalar vs array, and
        // contiguity gating. The actual element-wise loop is generated by
        // DirectILKernelGenerator.Clip as a DynamicMethod and cached per
        // (dtype, mode, kind). No SIMD width is hardcoded — the kernel adapts
        // to V128 / V256 / V512 via GetVectorContainerType().
        //
        // For strided / broadcast inputs that the contiguous IL kernel cannot
        // address directly, we materialize a contiguous copy first (`Cast(...,
        // copy: true)`) and then run the kernel in-place on that copy. This
        // is one extra memory pass for those inputs but keeps the kernel
        // surface area small.
        // =============================================================================

        public override NDArray ClipNDArray(NDArray lhs, NDArray min, NDArray max, Type dtype, NDArray @out = null)
            => ClipNDArray(lhs, min, max, dtype?.GetTypeCode(), @out);

        public override unsafe NDArray ClipNDArray(NDArray lhs, NDArray min, NDArray max, NPTypeCode? typeCode = null, NDArray @out = null)
        {
            // ---- Output dtype (explicit `dtype=` wins; otherwise NEP-50 weak-scalar promote)
            NPTypeCode outType;
            if (typeCode.HasValue)
                outType = typeCode.Value;
            else
            {
                outType = lhs.typecode;
                outType = PromoteClipBound(outType, min);
                outType = PromoteClipBound(outType, max);
            }

            // ---- @out validation (shape, writeable, dtype)
            if (@out is not null)
            {
                NumSharpException.ThrowIfNotWriteable(@out.Shape);
                if (@out.Shape != lhs.Shape)
                    throw new ArgumentException($"@out's shape ({@out.Shape}) must match lhs's shape ({lhs.Shape}).'");
                if (@out.GetTypeCode != outType)
                    throw new ArgumentException(
                        $"Cannot cast ufunc 'clip' output from dtype('{outType.AsNumpyDtypeName()}') to dtype('{@out.GetTypeCode.AsNumpyDtypeName()}') with casting rule 'same_kind'.");
            }

            // ---- Empty input — bypass the kernel entirely
            if (lhs.size == 0)
                return @out ?? Cast(lhs, outType, copy: true);

            // ---- Both bounds null — clip is a typed copy
            if (min is null && max is null)
            {
                if (@out is null) return Cast(lhs, outType, copy: true);
                np.copyto(@out, Cast(lhs, outType, copy: false));
                return @out;
            }

            // ---- Special-case NaN scalar bounds on float dtypes (NumPy: entire
            //      result is NaN). The IL kernel uses Vector.Min/Max which on x86
            //      do not propagate NaN-in-bounds in the second-operand position
            //      consistently across vendors, so we short-circuit here.
            if ((outType == NPTypeCode.Single || outType == NPTypeCode.Double)
                && ScalarIsNaN(min) || ScalarIsNaN(max))
            {
                var nan = outType == NPTypeCode.Double
                    ? np.full(lhs.Shape, double.NaN)
                    : np.full(lhs.Shape, float.NaN);
                if (@out is null) return nan;
                np.copyto(@out, nan);
                return @out;
            }

            // ---- Decide bound kinds and route through DirectILKernelGenerator
            bool minScalar = min is null || min.ndim == 0;
            bool maxScalar = max is null || max.ndim == 0;
            bool allScalarBounds = minScalar && maxScalar;

            // Build dispatch tuple for the IL kernel
            DirectILKernelGenerator.ClipMode mode =
                min is null ? DirectILKernelGenerator.ClipMode.MaxOnly :
                max is null ? DirectILKernelGenerator.ClipMode.MinOnly :
                              DirectILKernelGenerator.ClipMode.BothBounds;
            DirectILKernelGenerator.ClipBoundsKind kind =
                allScalarBounds ? DirectILKernelGenerator.ClipBoundsKind.Scalar
                                : DirectILKernelGenerator.ClipBoundsKind.Array;

            // Cast bounds to outType. For scalar (0-d) bounds astype is O(1);
            // for array bounds it's broadcast_to(target_shape) + astype, with
            // the same-shape/same-dtype short-circuit handled by PrepareBound.
            NDArray loCast = null, hiCast = null;
            if (kind == DirectILKernelGenerator.ClipBoundsKind.Scalar)
            {
                if (min is not null) loCast = min.astype(outType);
                if (max is not null) hiCast = max.astype(outType);
            }
            else
            {
                loCast = PrepareBound(min, lhs.Shape, outType);
                hiCast = PrepareBound(max, lhs.Shape, outType);
            }

            // ---- Pick src / dst pointers and materialize what's needed
            NDArray src, dst;
            bool srcDstSame;
            bool srcContiguous = lhs.Shape.IsContiguous && lhs.Shape.Offset == 0;
            // Array bounds feed the flat clip kernel, which walks src/dst/lo/hi
            // linearly and pairs them by C-order (row-major) index. Every operand
            // must therefore be C-contiguous offset-0; an F-contig / strided buffer
            // would be read in its raw buffer order and each element mis-paired
            // with the wrong bound (the W7-A "F-contig/strided wrong pairing" bug).
            // Scalar bounds are order-insensitive (one value broadcast to every
            // lane), so this normalization is needed only for array bounds.
            bool arrayBounds = kind == DirectILKernelGenerator.ClipBoundsKind.Array;
            // When @out is non-C-contiguous and bounds are arrays we cannot clip
            // in @out's own buffer (wrong element order vs the C-order bounds).
            // Clip a C-order temp and copy the logical result back into @out.
            NDArray copyBackOut = null;

            if (@out is not null)
            {
                if (arrayBounds && (!@out.Shape.IsContiguous || @out.Shape.Offset != 0))
                {
                    // @out is F-contig / strided: clip a C-order copy of lhs, then
                    // map it back into @out's layout via copyto (which honors strides).
                    dst = AsCContiguousCopy(lhs, outType);
                    src = dst;
                    srcDstSame = true;
                    copyBackOut = @out;
                }
                else
                {
                    // User-supplied @out — copy lhs (possibly cast) into it, run in-place.
                    np.copyto(@out, Cast(lhs, outType, copy: false));
                    dst = @out;
                    src = @out;          // run in place — fused copy already done via copyto above
                    srcDstSame = true;
                }
            }
            else if (allScalarBounds && srcContiguous && lhs.GetTypeCode == outType)
            {
                // Fused single-pass: read from lhs, write to a fresh dst — kernel
                // does Min(Max(src, lo), hi) and stores to dst in one memory pass.
                dst = np.empty(lhs.Shape, outType);
                src = lhs;
                srcDstSame = false;
            }
            else
            {
                // General path: materialize a contiguous outType-typed copy and clip in place.
                dst = Cast(lhs, outType, copy: true);
                // Cast keeps the source layout (order='K'); the flat array-bounds
                // kernel needs C-order, so re-materialize a C-contiguous copy when
                // lhs (hence dst) is F-contig / strided / offset.
                if (arrayBounds && (!dst.Shape.IsContiguous || dst.Shape.Offset != 0))
                    dst = dst.copy('C');
                src = dst;
                srcDstSame = true;
            }

            // ---- Invoke the IL-generated kernel
            void* srcPtr = (void*)src.Address;
            void* dstPtr = (void*)dst.Address;
            void* loPtr  = loCast is null ? null : (void*)loCast.Address;
            void* hiPtr  = hiCast is null ? null : (void*)hiCast.Address;

            DirectILKernelGenerator.Clip(outType, mode, kind, srcPtr, dstPtr, dst.size, loPtr, hiPtr);

            _ = srcDstSame;
            if (copyBackOut is not null)
            {
                // Array-bounds path computed into a C-order temp because @out's own
                // layout (F-contig / strided) can't drive the flat kernel; relay the
                // logical result into @out (copyto maps C-order → @out's strides).
                np.copyto(copyBackOut, dst);
                return copyBackOut;
            }
            return dst;
        }

        // ---- Policy helpers ---------------------------------------------------

        // NEP-50 weak-scalar promotion: a 0-d bound of the same kind
        // (int / float / complex / decimal) as outType is "weak" and doesn't
        // promote, mirroring how NumPy treats Python int/float literals.
        // Array bounds and cross-kind scalars promote via np.result_type.
        private static NPTypeCode PromoteClipBound(NPTypeCode outType, NDArray bound)
        {
            if (bound is null) return outType;
            if (bound.ndim == 0 && IsSameKind(outType, bound.typecode))
                return outType;
            return np.result_type(outType, bound.typecode);
        }

        private static bool IsSameKind(NPTypeCode a, NPTypeCode b)
        {
            int ga = a.GetGroup();
            int gb = b.GetGroup();
            // 0=Byte/Char, 1=signed int, 2=unsigned int  →  all "integer kind".
            bool aInt = ga >= 0 && ga <= 2;
            bool bInt = gb >= 0 && gb <= 2;
            if (aInt && bInt) return true;
            return ga == gb;
        }

        // Returns `bound` ready for the array-bounds kernel: matches lhs shape,
        // dtype outType, contiguous, offset zero. Returns the original instance
        // when those already hold (skips the otherwise-mandatory clone done by
        // `astype` on a same-dtype input).
        private static NDArray PrepareBound(NDArray bound, Shape targetShape, NPTypeCode outType)
        {
            if (bound is null) return null;
            if (bound.GetTypeCode == outType
                && bound.Shape.Equals(targetShape)
                && bound.Shape.IsContiguous
                && bound.Shape.Offset == 0)
            {
                return bound;
            }
            var prepared = np.broadcast_to(bound, targetShape).astype(outType);
            // The flat clip kernel reads lo/hi linearly in C-order. astype keeps
            // the source layout (order='K'), so an F-contig / strided / broadcast
            // bound stays non-C-contiguous and would be mis-paired element-wise
            // against the C-order src. Force a C-order copy when it isn't already
            // C-contiguous offset-0.
            if (!prepared.Shape.IsContiguous || prepared.Shape.Offset != 0)
                prepared = prepared.copy('C');
            return prepared;
        }

        // Materialize lhs as a fresh C-contiguous, offset-0 array of outType whose
        // element values are in logical (row-major) order. Used when the flat clip
        // kernel needs a C-order working buffer but the natural source/@out is
        // F-contig / strided and therefore can't drive the kernel directly.
        private NDArray AsCContiguousCopy(NDArray lhs, NPTypeCode outType)
        {
            var cast = Cast(lhs, outType, copy: true);
            if (!cast.Shape.IsContiguous || cast.Shape.Offset != 0)
                cast = cast.copy('C');
            return cast;
        }

        // Returns true when `bound` is a 0-d scalar NDArray whose value is NaN.
        // Used to short-circuit float NaN-in-bounds → all-NaN result (NumPy).
        private static bool ScalarIsNaN(NDArray bound)
        {
            if (bound is null || bound.ndim != 0) return false;
            switch (bound.GetTypeCode)
            {
                case NPTypeCode.Double: return double.IsNaN(bound.GetDouble(0));
                case NPTypeCode.Single: return float.IsNaN(bound.GetSingle(0));
                case NPTypeCode.Half:   return Half.IsNaN(bound.GetHalf(0));
                default: return false;
            }
        }
    }
}
