using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using NumSharp.Tests.Fuzz.RandomApi;

namespace NumSharp.Tests.Fuzz
{
    public partial class FuzzCorpusTests
    {
        // ---- the random-API oracle (docs/plans/random-oracle-coverage.md) -----------------------------------------------
        //
        // Every public member of the random world, by exact C# overload, against NumPy 2.4.2: the cases (generated by
        // test/oracle/gen_random_oracle.py) name the canonical signature they exercise, the harness (Fuzz/RandomApi/)
        // resolves and invokes exactly that member, and each case compares NumPy's result AND the receiver's full state
        // after the call (stream position, buffered 32-bit half, RandomState's Gaussian cache).

        /// <summary>
        ///     Random-API oracle, PORTABLE tier: members whose results are libm-free (raw bits, bounded integers, uniform
        ///     transforms, permutations, state and seeding) — byte-identical on every host, hard-gated everywhere.
        /// </summary>
        [TestMethod]
        [TestCategory("FuzzMatrix")]
        public void RandomApi() => RunRandomApiCorpus("random_api.jsonl");

        /// <summary>
        ///     Random-API oracle, HOST-LIBM tier: transform and rejection samplers whose values consume log/exp/pow/expm1.
        ///     Authored against the win-amd64 CRT, so hard-gated on Windows and Inconclusive elsewhere (the
        ///     random_parity_host pattern).
        /// </summary>
        [TestMethod]
        [TestCategory("FuzzMatrix")]
        public void RandomApiHostLibm()
        {
            if (!System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.Windows))
                Assert.Inconclusive("random_api_host.jsonl is authored against the win-amd64 CRT libm; transform/rejection " +
                                    "sampler streams are libm-dependent by construction.");
            RunRandomApiCorpus("random_api_host.jsonl");
        }

        /// <summary>
        ///     Random-API oracle, MULTIVARIATE-NORMAL tier: <c>multivariate_normal</c> on both APIs — NumPy factorises the
        ///     covariance (svd / eigh / cholesky) and multiplies the normal draws through its own scipy-openblas, so the
        ///     bytes are reproducible only through that same library at one thread (the <c>linalg_parity</c> pin), and the
        ///     normal draws consume the win-amd64 CRT's log/sqrt.
        /// </summary>
        /// <remarks>
        ///     Inconclusive off Windows (libm) and wherever the pinned OpenBLAS cannot be loaded; the backend is enabled for
        ///     the replay and disabled after it (process-global, hence <see cref="DoNotParallelizeAttribute"/>).
        /// </remarks>
        [TestMethod]
        [TestCategory("FuzzMatrix")]
        [DoNotParallelize]
        public void RandomApiMultivariateNormal()
        {
            if (!System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.Windows))
                Assert.Inconclusive("random_api_mvn.jsonl is authored against the win-amd64 CRT libm (the normal draws).");
            var pin = MatmulParityPin.Load("linalg_parity.host.jsonl");
            string mismatch = pin.TryEnableParityBackend();
            if (mismatch != null)
                Assert.Inconclusive(mismatch);
            try
            {
                RunRandomApiCorpus("random_api_mvn.jsonl");
            }
            finally
            {
                NumSharp.Interop.OpenBLAS.OpenBlasEngine.Disable();
            }
        }

        /// <summary>
        ///     Random-API oracle, LP64 tier: the legacy integer samplers' cases whose NumPy answer depends on C long being 64
        ///     bits — an element past the int32 range, or a bound derived from LONG_MAX (poisson's lam maximum, zipf's
        ///     rejection test, geometric's overflow value). NumSharp returns those samplers as int64 on every host, which is
        ///     the LP64 model, so their reference is Linux NumPy; win-amd64 NumPy answers them through a 32-bit long.
        /// </summary>
        /// <remarks>
        ///     Authored by Linux-x64 NumPy 2.4.2 (glibc libm) through the generator's WSL sub-run. Every answer in the tier
        ///     is an integer, and the tier was replayed green under both glibc (Linux .NET) and the win-amd64 CRT when it was
        ///     generated, so it is hard-gated on both x64 hosts. Other architectures/libms (macOS, arm64) report
        ///     Inconclusive: the samplers still consume log/exp/pow on the way to those integers, and no replay has verified
        ///     them there. A regeneration that turns a case libm-sensitive on Windows shows up here as a failure naming it.
        /// </remarks>
        [TestMethod]
        [TestCategory("FuzzMatrix")]
        public void RandomApiLp64()
        {
            bool x64 = System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture == System.Runtime.InteropServices.Architecture.X64;
            bool verifiedOs = System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.Windows)
                              || System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.Linux);
            if (!x64 || !verifiedOs)
                Assert.Inconclusive("random_api_lp64.jsonl is authored by Linux-x64 NumPy (glibc) and verified on x64 " +
                                    "Linux and Windows only; the samplers consume libm on the way to their integers.");
            RunRandomApiCorpus("random_api_lp64.jsonl");
        }

        /// <summary>
        ///     The environment variable naming a directory of random-API tiers generated with fresh seeds (the nightly soak,
        ///     <c>gen_random_oracle.py --seeds … --out DIR</c>); <see cref="RandomApiSoak"/> replays it and is Inconclusive
        ///     when it is unset.
        /// </summary>
        internal const string SoakDirVariable = "NUMSHARP_RANDOM_SOAK_DIR";

        /// <summary>
        ///     Committed floors for the random-API tiers: a truncated or partial regeneration (a family silently dropped, a
        ///     crashed run) fails the replay instead of passing on fewer cases. Set a little under the generated counts
        ///     (8,485 / 15,779 / 730 / 206 at P5; 9,820 / 15,795 / 730 / 234 after the wholeness pass, whose array- and
        ///     big-bounds <c>integers</c>/<c>randint</c> and module-class factories raised the portable floor from 8,300 —
        ///     the old one would have let that whole ~1,300-case family vanish), so an intended trim needs a deliberate floor
        ///     change. The soak corpora, generated by the same families from other seeds, are held to the same floors —
        ///     which is why the LP64 floor leaves more room: how many cases need Linux's 64-bit-long answer depends a little
        ///     on the seeds.
        /// </summary>
        internal static readonly Dictionary<string, int> RandomApiMinCases = new(StringComparer.Ordinal)
        {
            ["random_api.jsonl"] = 9_600,
            ["random_api_host.jsonl"] = 15_500,
            ["random_api_mvn.jsonl"] = 700,
            ["random_api_lp64.jsonl"] = 120,
        };

        /// <summary>
        ///     The nightly soak with fresh seeds (plan §6.7): replays every tier of the directory in
        ///     <see cref="SoakDirVariable"/> — regenerated by NumPy 2.4.2 from the same families under 10 seeds drawn that
        ///     night — through the same harness and comparator as the committed tiers. Each tier keeps its own gating:
        ///     the libm tier needs Windows, the multivariate-normal tier the pinned OpenBLAS, the LP64 tier x64 Windows or
        ///     Linux; a tier the host cannot judge is reported and skipped, and every other tier's divergences are
        ///     collected before the test fails.
        /// </summary>
        /// <remarks>
        ///     Inconclusive when the variable is unset (every per-push run). The directory must hold all four tiers: the
        ///     soak generation merges a Linux job's LP64 rows (<c>--lp64-rows</c>), so a missing tier means the pipeline
        ///     broke, which is a failure, not a skip.
        /// </remarks>
        [TestMethod]
        [TestCategory("FuzzMatrix")]
        [DoNotParallelize]
        public void RandomApiSoak()
        {
            string dir = Environment.GetEnvironmentVariable(SoakDirVariable);
            if (string.IsNullOrEmpty(dir))
                Assert.Inconclusive($"{SoakDirVariable} is not set: no fresh-seed random-API corpus to replay (the nightly soak sets it).");
            Assert.IsTrue(System.IO.Directory.Exists(dir), $"{SoakDirVariable}={dir} is not a directory");
            string manifest = System.IO.Path.Combine(dir, "manifest.json");
            if (System.IO.File.Exists(manifest))
                Console.WriteLine($"[RandomApiSoak] {System.IO.File.ReadAllText(manifest)}");

            bool windows = System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.Windows);
            bool linux = System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.Linux);
            bool x64 = System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture == System.Runtime.InteropServices.Architecture.X64;
            var failures = new List<string>();

            void Tier(string file, string skipReason = null)
            {
                string path = System.IO.Path.Combine(dir, file);
                if (!System.IO.File.Exists(path))
                {
                    failures.Add($"{file}: missing from the soak directory (the generation or the LP64 merge broke)");
                    return;
                }
                if (skipReason != null)
                {
                    Console.WriteLine($"[RandomApiSoak] {file}: skipped — {skipReason}");
                    return;
                }
                try
                {
                    RunRandomApiCorpus(file, dir);
                }
                catch (AssertFailedException e)
                {
                    failures.Add($"{file}: {e.Message}");
                }
            }

            Tier("random_api.jsonl");
            Tier("random_api_host.jsonl", windows ? null : "authored against the win-amd64 CRT libm");
            Tier("random_api_lp64.jsonl", x64 && (windows || linux) ? null : "verified on x64 Windows and Linux only");
            if (!windows)
                Tier("random_api_mvn.jsonl", "authored against the win-amd64 CRT libm");
            else
            {
                string mismatch = MatmulParityPin.Load("linalg_parity.host.jsonl").TryEnableParityBackend();
                if (mismatch != null)
                    Tier("random_api_mvn.jsonl", mismatch);
                else
                {
                    try
                    {
                        Tier("random_api_mvn.jsonl");
                    }
                    finally
                    {
                        NumSharp.Interop.OpenBLAS.OpenBlasEngine.Disable();
                    }
                }
            }
            if (failures.Count > 0)
                Assert.Fail($"random-API soak ({dir}): {failures.Count} tier(s) failed:\n" + string.Join("\n", failures));
        }

        /// <summary>
        ///     Replays one random-API tier: per case, NumPy's error (type + verbatim text) or NumPy's result observation plus
        ///     the receiver's post-call state text.
        /// </summary>
        /// <param name="file">The corpus file name (a committed tier under Fuzz/corpus/, or a soak tier in
        ///     <paramref name="directory"/>).</param>
        /// <param name="directory">A directory to read <paramref name="file"/> from instead of the test output's corpus
        ///     folder (the nightly soak's fresh-seed corpus), or null.</param>
        /// <remarks>
        ///     The loop never stops at the first divergence: every failing case is listed (capped at 60 lines), and every
        ///     excused one is printed with its reason, so one run shows the whole picture. Operands and NDArray results are
        ///     disposed per case, as the leak gates require of every replay.
        /// </remarks>
        /// <exception cref="AssertFailedException">A case diverged from NumPy, or the tier is below its floor.</exception>
        private static void RunRandomApiCorpus(string file, string directory = null)
        {
            using var cases = directory == null ? FuzzCorpus.Open(file) : new CorpusFile(file, System.IO.Path.Combine(directory, file));
            int floor = RandomApiMinCases.TryGetValue(file, out var f) ? f : 1;
            Assert.IsTrue(cases.Count >= floor, $"corpus '{file}' has {cases.Count} cases, below the committed floor of {floor}");

            var failures = new List<string>();
            var documented = new Dictionary<string, int>();
            // The slowest cases, reported after the replay: one expensive case in a tier of thousands is otherwise
            // invisible, and the tier's wall time is part of the suite's budget.
            var slowest = new List<(double ms, string id)>();
            var watch = new System.Diagnostics.Stopwatch();
            foreach (var c in cases)
            {
                var operands = new NDArray[c.Operands.Length];
                watch.Restart();
                try
                {
                    for (int i = 0; i < operands.Length; i++)
                        operands[i] = FuzzCorpus.Reconstruct(c.Operands[i]);
                    string reason = null;
                    string problem = c.Expects_Throw ? CheckRandomApiError(c, operands) : CheckRandomApiValue(c, operands, out reason);
                    if (reason != null)
                        Bump(documented, reason);
                    if (problem != null)
                        failures.Add($"{c.Id}: {problem}");
                }
                catch (Exception e)
                {
                    failures.Add($"{c.Id}: HARNESS {e.GetType().Name}: {e.Message}");
                }
                finally
                {
                    foreach (var o in operands)
                        o?.Dispose();
                }
                slowest.Add((watch.Elapsed.TotalMilliseconds, c.Id));
                if (slowest.Count > 64)
                {
                    slowest.Sort((a, b) => b.ms.CompareTo(a.ms));
                    slowest.RemoveRange(8, slowest.Count - 8);
                }
            }

            slowest.Sort((a, b) => b.ms.CompareTo(a.ms));
            Console.WriteLine($"[{file}] slowest cases: " +
                              string.Join("; ", slowest.Take(8).Select(s => $"{s.ms:F1} ms {s.id}")));
            if (documented.Count > 0)
                Console.WriteLine($"[{file}] documented divergences excused: " +
                                  string.Join("; ", documented.Select(kv => $"{kv.Value}x {kv.Key}")));
            if (failures.Count > 0)
            {
                // The full list goes to the test output; the assertion message keeps the first 60 readable.
                if (failures.Count > 60)
                    Console.WriteLine($"[{file}] all {failures.Count} divergences:\n  " + string.Join("\n  ", failures));
                Assert.Fail($"{failures.Count}/{cases.Count} random-API cases diverged from NumPy:\n  " +
                            string.Join("\n  ", failures.Take(60)));
            }
        }

        /// <summary>A value case: the result observation and the post-call state must equal NumPy's.</summary>
        /// <param name="c">The case.</param>
        /// <param name="operands">Its reconstructed operands.</param>
        /// <param name="documentedReason">Receives the documented reason when the result differs only within an intended,
        ///     bounded divergence (<see cref="RandomApiDivergences"/>); the state must still match exactly.</param>
        /// <returns>Null when both match (or the result is an excused divergence), else the first difference.</returns>
        private static string CheckRandomApiValue(FuzzCorpus.Case c, NDArray[] operands, out string documentedReason)
        {
            documentedReason = null;
            RandomApiHarness.Outcome outcome;
            try
            {
                outcome = RandomApiHarness.Run(c.Params, operands);
            }
            catch (Exception e) when (e is not NotSupportedException || !e.Message.StartsWith("the random-API", StringComparison.Ordinal))
            {
                // A documented divergence may be a throw where NumPy answers (a C# return type that cannot carry
                // NumPy's answer); anything else is a failure.
                documentedReason = RandomApiDivergences.ClassifyThrow(c, e);
                return documentedReason != null ? null : $"NumSharp threw {e.GetType().Name}: {e.Message} (NumPy returns a value)";
            }
            try
            {
                // Entropy-drawn state words are masked identically on both sides (the generator's state_mask).
                var mask = c.Params.TryGetValue("state_mask", out var m)
                    ? m.EnumerateArray().Select(x => x.GetString()).ToList()
                    : new List<string>();
                // A constructor is observed through the object it builds, not its `void` signature.
                string observedType = outcome.Member.Kind == "ctor" ? outcome.Member.DeclaringType : outcome.Member.Returns;
                var actual = RandomApiObservation.MaskObs(
                    RandomApiObservation.Observe(outcome.Result, observedType, c.Expected.Result), mask);
                string diff = RandomApiObservation.Diff(c.Expected.Result, actual);
                if (diff != null)
                {
                    documentedReason = RandomApiDivergences.ClassifyValue(c, c.Expected.Result, actual);
                    if (documentedReason == null)
                        return diff;
                }
                if (c.Expected.State != null)
                {
                    string state = RandomApiObservation.MaskText(RandomApiObservation.StateText(outcome.Receiver), mask);
                    if (state != c.Expected.State)
                        return $"state after the call differs (stream position / buffered half / gauss cache):\n" +
                               $"      numpy:    {c.Expected.State}\n      numsharp: {state}";
                }
                // Operands the member mutates in place: their contents after the call.
                if (c.Params.TryGetValue("watch", out var watch))
                {
                    int k = 0;
                    foreach (var idx in watch.EnumerateArray())
                    {
                        var after = RandomApiObservation.ArrayObs(operands[idx.GetInt32()]);
                        string afterDiff = RandomApiObservation.Diff(c.Expected.After[k], after, $"after[{k}]");
                        if (afterDiff != null)
                            return afterDiff;
                        k++;
                    }
                }
                return null;
            }
            finally
            {
                if (outcome.Result is NDArray r && !IsOperand(operands, r))
                    r.Dispose();
            }
        }

        /// <summary>
        ///     Whether a result IS one of the case's operands (by reference: a member returning its argument), so the replay
        ///     leaves its disposal to the operand pass. Never <c>Contains</c>: NDArray equality is elementwise and throws
        ///     on shapes that do not broadcast.
        /// </summary>
        /// <param name="operands">The case's operands.</param>
        /// <param name="r">The result.</param>
        /// <returns>True when <paramref name="r"/> is an operand instance.</returns>
        private static bool IsOperand(NDArray[] operands, NDArray r)
        {
            foreach (var o in operands)
                if (ReferenceEquals(o, r))
                    return true;
            return false;
        }

        /// <summary>An error case: NumSharp must throw a plausible counterpart of NumPy's exception with NumPy's text.</summary>
        /// <param name="c">The case.</param>
        /// <param name="operands">Its reconstructed operands.</param>
        /// <returns>Null when the error matches, else the difference.</returns>
        private static string CheckRandomApiError(FuzzCorpus.Case c, NDArray[] operands)
        {
            RandomApiHarness.Outcome outcome;
            try
            {
                outcome = RandomApiHarness.Run(c.Params, operands);
            }
            catch (Exception e)
            {
                string gotType = e.GetType().Name;
                string gotText = NormalizeMessage(e.Message);
                bool typeOk = gotType == c.Error.Type
                              || !ErrorTypeMap.TryGetValue(c.Error.Type, out var allowed)
                              || allowed.Contains(gotType);
                bool textOk = string.Equals(gotText, c.Error.Text ?? "", StringComparison.Ordinal);
                return typeOk && textOk ? null
                    : $"error mismatch\n      numpy:    {c.Error.Type}: {Show(c.Error.Text)}\n      numsharp: {gotType}: {Show(gotText)}";
            }
            if (outcome.Result is NDArray r && !IsOperand(operands, r))
                r.Dispose();
            return $"NumPy raises {c.Error.Type} ({Show(c.Error.Text)}) but NumSharp returned a value";
        }
    }
}
