using System;
using System.Collections.Generic;
using System.Linq;
using AwesomeAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using NumSharp;
using NumSharp.Generic;
using NumSharp.UnitTest.Utilities;

namespace NumSharp.UnitTest.Selection
{
    /// <summary>
    /// Differential probe matrices for boolean-mask and combined boolean+advanced
    /// indexing, replayed as committed tests. Every case was generated by running the
    /// equivalent expression in NumPy 2.4.2 (the oracle scripts in test/oracle-style
    /// probing) and is pinned here: each NumSharp result must match NumPy's shape and
    /// C-order values, or raise where NumPy raises. DynamicData gives one reportable
    /// test per case.
    /// </summary>
    [TestClass]
    public class IndexingProbeMatrix_Tests
    {
        private static NDArray<bool> M(params bool[] b) => np.array(b).MakeGeneric<bool>();
        private static NDArray<bool> M0(bool b) => np.array(b).MakeGeneric<bool>();          // 0-D mask
        private static NDArray<bool> M2(bool[,] b) => np.array(b).MakeGeneric<bool>();        // 2-D mask
        private static NDArray A() => np.arange(12).reshape(3, 4);
        private static NDArray B() => np.arange(24).reshape(2, 3, 4);

        // ── case records ───────────────────────────────────────────────────────────
        public sealed record GCase(string Name, Func<NDArray> Op, int[] Shape, long[] Vals);
        public sealed record ECase(string Name, Func<NDArray> Op);

        private static void AssertGet(GCase c)
        {
            var r = c.Op();
            r.shape.Select(x => (int)x).ToArray().Should().Equal(c.Shape, $"{c.Name} shape");
            if (c.Vals == null) return;                                  // shape-only case
            var flat = new long[r.size];
            var f = r.flat;
            for (long i = 0; i < r.size; i++) flat[i] = Convert.ToInt64(f.GetValue(i));
            flat.Should().Equal(c.Vals, $"{c.Name} values");
        }

        // ═══════════════════════════ BOOLEAN MASK — GET ════════════════════════════
        private static readonly GCase[] BoolGet =
        {
            new("g01_full1d",        () => np.arange(6)[M(true,false,true,false,true,false)], new[]{3}, new long[]{0,2,4}),
            new("g02_full2d",        () => { var a=A(); return a[(a%2)==0]; }, new[]{6}, new long[]{0,2,4,6,8,10}),
            new("g03_axis0",         () => A()[M(true,false,true)], new[]{2,4}, new long[]{0,1,2,3,8,9,10,11}),
            new("g04_partial3d",     () => B()[M2(new[,]{{true,false,true},{false,true,false}})], new[]{3,4}, new long[]{0,1,2,3,8,9,10,11,16,17,18,19}),
            new("g05_allTrue",       () => { var a=A(); return a[np.ones(new Shape(3,4),np.bool_).MakeGeneric<bool>()]; }, new[]{12}, new long[]{0,1,2,3,4,5,6,7,8,9,10,11}),
            new("g06_allFalse",      () => { var a=A(); return a[np.zeros(new Shape(3,4),np.bool_).MakeGeneric<bool>()]; }, new[]{0}, new long[]{}),
            new("g07_allFalse_ax0",  () => A()[M(false,false,false)], new[]{0,4}, new long[]{}),
            new("g08_0dTrue",        () => A()[M0(true)], new[]{1,3,4}, new long[]{0,1,2,3,4,5,6,7,8,9,10,11}),
            new("g09_0dFalse",       () => A()[M0(false)], new[]{0,3,4}, new long[]{}),
            new("g10_1elem1d",       () => np.array(new long[]{7})[M(true)], new[]{1}, new long[]{7}),
            new("g11_Fcontig",       () => { var a=np.asfortranarray(A()); return a[(a%2)==0]; }, new[]{6}, new long[]{0,2,4,6,8,10}),
            new("g12_transposed",    () => { var a=A().T; return a[(a%2)==0]; }, new[]{6}, new long[]{0,4,8,2,6,10}),
            new("g13_negstride",     () => { var a=A()["::-1"]; return a[(a%2)==0]; }, new[]{6}, new long[]{8,10,4,6,0,2}),
            new("g14_sliced_off",    () => { var a=np.arange(20)["5:"]; return a[a>10]; }, new[]{9}, new long[]{11,12,13,14,15,16,17,18,19}),
            new("g15_colslice",      () => { var a=A()[":, 1:3"]; return a[(a%2)==0]; }, new[]{3}, new long[]{2,6,10}),
            new("g16_bcast_arr",     () => { var a=np.broadcast_to(np.arange(4),new Shape(3,4)); return a[(a%2)==0]; }, new[]{6}, new long[]{0,2,0,2,0,2}),
            new("g17_mask_negstr",   () => np.arange(5)[M(true,false,true,false,true)["::-1"].MakeGeneric<bool>()], new[]{3}, new long[]{0,2,4}),
            new("g18_mask_Fcontig",  () => { var a=A(); return a[np.asfortranarray((a%2)==0).MakeGeneric<bool>()]; }, new[]{6}, new long[]{0,2,4,6,8,10}),
            new("g19_scalar0d",      () => np.array(5L)[M0(true)], new[]{1}, new long[]{5}),
            new("g20_4d_full",       () => { var a=np.arange(16).reshape(2,2,2,2); return a[(a%3)==0]; }, new[]{6}, new long[]{0,3,6,9,12,15}),
            new("g21_empty_arr",     () => { var a=np.zeros(new Shape(0,3)); return a[np.zeros(new Shape(0,3),np.bool_).MakeGeneric<bool>()]; }, new[]{0}, new long[]{}),
            new("g22_empty_ax0",     () => { var a=np.zeros(new Shape(0,3)); return a[np.zeros(new Shape(0),np.bool_).MakeGeneric<bool>()]; }, new[]{0,3}, new long[]{}),
            new("g23_uint8_is_fancy",() => np.arange(5)[np.array(new byte[]{1,0,1,0,1})], new[]{5}, new long[]{1,0,1,0,1}),
            new("g24_1elem2d",       () => np.array(new long[,]{{5}})[M2(new[,]{{true}})], new[]{1}, new long[]{5}),
            new("g25_partial_Fcontig",() => np.asfortranarray(B())[M2(new[,]{{true,false,true},{false,true,false}})], new[]{3,4}, new long[]{0,1,2,3,8,9,10,11,16,17,18,19}),
        };

        private static readonly ECase[] BoolGetErr =
        {
            new("e01_mask_short",  () => np.arange(5)[M(true,false,true)]),
            new("e02_mask_long",   () => np.arange(5)[M(true,false,true,false,true,true)]),
            new("e03_mask_ndim_gt",() => np.arange(3)[M2(new[,]{{true,false,true}})]),
        };

        // ═══════════════════════════ BOOLEAN MASK — SET ════════════════════════════
        public sealed record SCase(string Name, Func<NDArray> Op, long[] Vals);

        private static readonly SCase[] BoolSet =
        {
            new("s01_full_scalar",  () => { var a=A(); a[(a%2)==0]=(NDArray)(-1L); return a; }, new long[]{-1,1,-1,3,-1,5,-1,7,-1,9,-1,11}),
            new("s02_full_array",   () => { var a=A(); a[(a%3)==0]=np.array(new long[]{100,200,300,400}); return a; }, new long[]{100,1,2,200,4,5,300,7,8,400,10,11}),
            new("s03_axis0_scalar", () => { var a=A(); a[M(true,false,true)]=(NDArray)(-9L); return a; }, new long[]{-9,-9,-9,-9,4,5,6,7,-9,-9,-9,-9}),
            new("s04_axis0_rowbc",  () => { var a=A(); a[M(true,false,true)]=np.array(new long[]{10,20,30,40}); return a; }, new long[]{10,20,30,40,4,5,6,7,10,20,30,40}),
            new("s05_axis0_perrow", () => { var a=A(); a[M(true,false,true)]=np.array(new long[,]{{1,2,3,4},{5,6,7,8}}); return a; }, new long[]{1,2,3,4,4,5,6,7,5,6,7,8}),
            new("s06_axis0_count1", () => { var a=A(); a[M(true,false,true)]=np.array(new long[,]{{10},{20}}); return a; }, new long[]{10,10,10,10,4,5,6,7,20,20,20,20}),
            new("s07_cast_f2i",     () => { var a=A(); a[(a%2)==0]=(NDArray)3.9; return a; }, new long[]{3,1,3,3,3,5,3,7,3,9,3,11}),
            new("s08_empty_mask",   () => { var a=A(); a[a>1000]=(NDArray)(-1L); return a; }, new long[]{0,1,2,3,4,5,6,7,8,9,10,11}),
            new("s09_0dval",        () => { var a=A(); a[(a%2)==0]=np.array(5L); return a; }, new long[]{5,1,5,3,5,5,5,7,5,9,5,11}),
            new("s10_0dTrue_set",   () => { var a=A(); a[M0(true)]=(NDArray)0L; return a; }, new long[]{0,0,0,0,0,0,0,0,0,0,0,0}),
            new("s11_negstride_set",() => { var a=A(); var v=a["::-1"]; v[(v%2)==0]=(NDArray)(-1L); return a; }, new long[]{-1,1,-1,3,-1,5,-1,7,-1,9,-1,11}),
            new("s12_partial_scalar",() => { var a=B(); a[M2(new[,]{{true,false,true},{false,true,false}})]=(NDArray)(-7L); return a; }, new long[]{-7,-7,-7,-7,4,5,6,7,-7,-7,-7,-7,12,13,14,15,-7,-7,-7,-7,20,21,22,23}),
            new("s13_partial_block",() => { var a=B(); a[M2(new[,]{{true,false,true},{false,true,false}})]=np.array(new long[,]{{1,2,3,4},{5,6,7,8},{9,10,11,12}}); return a; }, new long[]{1,2,3,4,4,5,6,7,5,6,7,8,12,13,14,15,9,10,11,12,20,21,22,23}),
            new("s14_colslice_set", () => { var a=A(); var v=a[":, 1:3"]; v[(v%2)==0]=(NDArray)(-5L); return a; }, new long[]{0,1,-5,3,4,5,-5,7,8,9,-5,11}),
        };

        private static readonly ECase[] BoolSetErr =
        {
            new("se01_full_badval",  () => { var a=A(); a[(a%2)==0]=np.array(new long[]{1,2,3}); return a; }),
            new("se02_axis0_count",  () => { var a=A(); a[M(true,false,true)]=np.array(new long[]{10,20}); return a; }),
            new("se03_nonwriteable", () => { var a=np.broadcast_to(np.arange(4),new Shape(3,4)); a[(a%2)==0]=(NDArray)(-1L); return a; }),
            new("se04_val_toolong",  () => { var a=A(); a[(a%3)==0]=np.array(new long[]{1,2,3,4,5}); return a; }),
        };

        // ═══════════════════════ COMBINED (mask + advanced) — GET ══════════════════
        private static readonly GCase[] CombGet =
        {
            new("c01_mask_int",      () => A()[M(true,false,true), 2], new[]{2}, new long[]{2,10}),
            new("c02_int_mask",      () => A()[1, M(true,false,true,false)], new[]{2}, new long[]{4,6}),
            new("c03_mask_slice",    () => A()[M(true,false,true), "1:3"], new[]{2,2}, new long[]{1,2,9,10}),
            new("c04_slice_mask",    () => A()[":", M(true,false,true,false)], new[]{3,2}, new long[]{0,2,4,6,8,10}),
            new("c05_mask_colon",    () => A()[M(true,false,true), ":"], new[]{2,4}, new long[]{0,1,2,3,8,9,10,11}),
            new("c06_mask_mask",     () => A()[M(true,false,true), M(true,false,true,false)], new[]{2}, new long[]{0,10}),
            new("c07_maskrow_intarr",() => A()[M(true,true,false), np.array(new long[]{0,3})], new[]{2}, new long[]{0,7}),
            new("c08_2dmask_int",    () => B()[M2(new[,]{{true,false,true},{false,true,false}}), 1], new[]{3}, new long[]{1,9,17}),
            new("c09_int_mask_int",  () => B()[0, M(true,false,true), 2], new[]{2}, new long[]{2,10}),
            new("c10_mask_negint",   () => A()[M(true,false,true), -1], new[]{2}, new long[]{3,11}),
            new("c11_mask_negarr",   () => A()[M(true,false,true), np.array(new long[]{-1,-2})], new[]{2}, new long[]{3,10}),
            new("c12_negint_mask",   () => A()[-1, M(true,false,true,false)], new[]{2}, new long[]{8,10}),
            new("c13_revslice_mask", () => A()["::-1", M(true,false,true,false)], new[]{3,2}, new long[]{8,10,4,6,0,2}),
            new("c14_mask_stepslice",() => A()[M(true,false,true), "::2"], new[]{2,2}, new long[]{0,2,8,10}),
            new("c15_stepslice_mask",() => A()["::2", M(true,false,true,false)], new[]{2,2}, new long[]{0,2,8,10}),
            new("c16_emptymask_int", () => A()[M(false,false,false), 2], new[]{0}, new long[]{}),
            new("c17_emptymask_slice",() => A()[M(false,false,false), "1:3"], new[]{0,2}, new long[]{}),
            new("c18_singlemask_int",() => A()[M(false,true,false), 2], new[]{1}, new long[]{6}),
            new("c19_slice_emptymask",() => A()[":", M(false,false,false,false)], new[]{3,0}, new long[]{}),
            new("c20_slice_mask_sl", () => B()[":", M(true,false,true), ":"], new[]{2,2,4}, new long[]{0,1,2,3,8,9,10,11,12,13,14,15,20,21,22,23}),
            new("c21_int_mask_slice",() => B()[1, M(true,false,true), ":"], new[]{2,4}, new long[]{12,13,14,15,20,21,22,23}),
            new("c22_mask_slice_int",() => B()[M(true,false), "1:3", 2], new[]{1,2}, new long[]{6,10}),
            new("c23_4d_slice_mask", () => np.arange(120).reshape(2,3,4,5)[":", ":", M(true,false,true,false), ":"], new[]{2,3,2,5}, null),
            new("c24_mask_ellipsis", () => B()[M(true,false), "..."], new[]{1,3,4}, new long[]{0,1,2,3,4,5,6,7,8,9,10,11}),
            new("c25_ellipsis_mask", () => B()["...", M(true,false,true,false)]["...", 0], new[]{2,3}, new long[]{0,4,8,12,16,20}),
            new("c26_2dmask_slice",  () => B()[M2(new[,]{{true,false,true},{false,true,false}}), "1:3"], new[]{3,2}, new long[]{1,2,9,10,17,18}),
            new("c27_2dmask_colon",  () => B()[M2(new[,]{{true,false,true},{false,true,false}}), ":"], new[]{3,4}, new long[]{0,1,2,3,8,9,10,11,16,17,18,19}),
            new("c28_transp_mask_int",() => A().T[M(true,false,true,false), 1], new[]{2}, new long[]{4,6}),
            new("c29_mask_newaxis",  () => A()[M(true,false,true), Slice.NewAxis], new[]{2,1,4}, new long[]{0,1,2,3,8,9,10,11}),
            new("c30_newaxis_mask",  () => A()[Slice.NewAxis, M(true,false,true)], new[]{1,2,4}, new long[]{0,1,2,3,8,9,10,11}),
            new("c31_slice_intarr",  () => A()[":", np.array(new long[]{0,2})], new[]{3,2}, new long[]{0,2,4,6,8,10}),
        };

        // ═══════════════════════ COMBINED (mask + advanced) — SET ══════════════════
        private static readonly SCase[] CombSet =
        {
            new("cs01_mask_int",     () => { var a=A(); a[M(true,false,true),2]=(NDArray)(-1L); return a; }, new long[]{0,1,-1,3,4,5,6,7,8,9,-1,11}),
            new("cs02_slice_mask",   () => { var a=A(); a[":",M(true,false,true,false)]=(NDArray)(-1L); return a; }, new long[]{-1,1,-1,3,-1,5,-1,7,-1,9,-1,11}),
            new("cs03_int_mask",     () => { var a=A(); a[1,M(true,false,true,false)]=(NDArray)(-1L); return a; }, new long[]{0,1,2,3,-1,5,-1,7,8,9,10,11}),
            new("cs04_mask_slice",   () => { var a=A(); a[M(true,false,true),"1:3"]=(NDArray)(-1L); return a; }, new long[]{0,-1,-1,3,4,5,6,7,8,-1,-1,11}),
            new("cs05_mask_colon",   () => { var a=A(); a[M(true,false,true),":"]=(NDArray)(-1L); return a; }, new long[]{-1,-1,-1,-1,4,5,6,7,-1,-1,-1,-1}),
            new("cs06_slice_intarr", () => { var a=A(); a[":",np.array(new long[]{0,2})]=(NDArray)(-1L); return a; }, new long[]{-1,1,-1,3,-1,5,-1,7,-1,9,-1,11}),
            new("cs07_mask_negint",  () => { var a=A(); a[M(true,false,true),-1]=(NDArray)(-1L); return a; }, new long[]{0,1,2,-1,4,5,6,7,8,9,10,-1}),
            new("cs08_mask_stepsl",  () => { var a=A(); a[M(true,false,true),"::2"]=(NDArray)(-1L); return a; }, new long[]{-1,1,-1,3,4,5,6,7,-1,9,-1,11}),
            new("cs09_negint_mask",  () => { var a=A(); a[-1,M(true,false,true,false)]=(NDArray)(-5L); return a; }, new long[]{0,1,2,3,4,5,6,7,-5,9,-5,11}),
            new("cs10_slice_mask_grid",() => { var a=A(); a[":",M(true,false,true,false)]=np.array(new long[,]{{1,2},{3,4},{5,6}}); return a; }, new long[]{1,1,2,3,3,5,4,7,5,9,6,11}),
            new("cs11_mask_intvec",  () => { var a=A(); a[M(true,false,true),"1:3"]=np.array(new long[]{10,20}); return a; }, new long[]{0,10,20,3,4,5,6,7,8,10,20,11}),
            new("cs12_slice_mask_sl",() => { var a=B(); a[":",M(true,false,true),":"]=(NDArray)(-7L); return a; }, new long[]{-7,-7,-7,-7,4,5,6,7,-7,-7,-7,-7,-7,-7,-7,-7,16,17,18,19,-7,-7,-7,-7}),
            new("cs13_2dmask_slice", () => { var a=B(); a[M2(new[,]{{true,false,true},{false,true,false}}),"1:3"]=(NDArray)(-1L); return a; }, new long[]{0,-1,-1,3,4,5,6,7,8,-1,-1,11,12,13,14,15,16,-1,-1,19,20,21,22,23}),
        };

        private static readonly ECase[] CombSetErr =
        {
            new("cse01_slice_mask_vecmismatch", () => { var a=A(); a[":",M(true,false,true,false)]=np.array(new long[]{100,200,300}); return a; }),
            new("cse02_mask_slice_badval",      () => { var a=A(); a[M(true,false,true),"1:3"]=np.array(new long[]{1,2,3,4,5}); return a; }),
        };

        // ── DynamicData sources (index + name for readable reporting) ───────────────
        private static IEnumerable<object[]> Idx<T>(T[] arr, Func<T, string> name)
            => arr.Select((c, i) => new object[] { i, name(c) });

        public static IEnumerable<object[]> BoolGetData => Idx(BoolGet, c => c.Name);
        public static IEnumerable<object[]> BoolGetErrData => Idx(BoolGetErr, c => c.Name);
        public static IEnumerable<object[]> BoolSetData => Idx(BoolSet, c => c.Name);
        public static IEnumerable<object[]> BoolSetErrData => Idx(BoolSetErr, c => c.Name);
        public static IEnumerable<object[]> CombGetData => Idx(CombGet, c => c.Name);
        public static IEnumerable<object[]> CombSetData => Idx(CombSet, c => c.Name);
        public static IEnumerable<object[]> CombSetErrData => Idx(CombSetErr, c => c.Name);

        // ── tests ───────────────────────────────────────────────────────────────────
        [DataTestMethod, DynamicData(nameof(BoolGetData))]
        public void BooleanMask_Get(int i, string name) => AssertGet(BoolGet[i]);

        [DataTestMethod, DynamicData(nameof(BoolGetErrData))]
        public void BooleanMask_Get_Throws(int i, string name)
        {
            Action act = () => { var _ = BoolGetErr[i].Op(); };
            act.Should().Throw<Exception>(name);
        }

        [DataTestMethod, DynamicData(nameof(BoolSetData))]
        public void BooleanMask_Set(int i, string name)
        {
            var r = BoolSet[i].Op();
            var flat = new long[r.size];
            var f = r.flat;
            for (long k = 0; k < r.size; k++) flat[k] = Convert.ToInt64(f.GetValue(k));
            flat.Should().Equal(BoolSet[i].Vals, name);
        }

        [DataTestMethod, DynamicData(nameof(BoolSetErrData))]
        public void BooleanMask_Set_Throws(int i, string name)
        {
            Action act = () => { var _ = BoolSetErr[i].Op(); };
            act.Should().Throw<Exception>(name);
        }

        [DataTestMethod, DynamicData(nameof(CombGetData))]
        public void Combined_Get(int i, string name) => AssertGet(CombGet[i]);

        [DataTestMethod, DynamicData(nameof(CombSetData))]
        public void Combined_Set(int i, string name)
        {
            var r = CombSet[i].Op();
            var flat = new long[r.size];
            var f = r.flat;
            for (long k = 0; k < r.size; k++) flat[k] = Convert.ToInt64(f.GetValue(k));
            flat.Should().Equal(CombSet[i].Vals, name);
        }

        [DataTestMethod, DynamicData(nameof(CombSetErrData))]
        public void Combined_Set_Throws(int i, string name)
        {
            Action act = () => { var _ = CombSetErr[i].Op(); };
            act.Should().Throw<Exception>(name);
        }
    }
}
